function Ssig = VBOX3iSL_solution_type721
%****************************************************
% D:\tools\matlab\contiguard\dbc\VBOX3iSL_solution_type721.m */
% aus dbc-File: D:\tools\matlab\contiguard\dbc\VBOX3iSL_solution_type721.dbc */
%****************************************************
  c = ...
  {{                  'name_in','unit_in','lin_in',                      'name_out','unit_out','comment'} ...
  ,{'Sats'                     ,'Sats'   ,0       ,'VBox_Sats'                     ,'Sats'    ,''       } ...
  ,{'Latitude'                 ,'Minutes',1       ,'VBox_Latitude'                 ,'Minutes' ,''       } ...
  ,{'Longitude'                ,'Minutes',1       ,'VBox_Longitude'                ,'Minutes' ,''       } ...
  ,{'Velocity_kmh'             ,'Km/h'   ,1       ,'VBox_Velocity_kmh'             ,'Km/h'    ,''       } ...
  ,{'Heading'                  ,'Degrees',1       ,'VBox_Heading'                  ,'Degrees' ,''       } ...
  ,{'DGPS'                     ,'On'     ,0       ,'VBox_DGPS'                     ,'On'      ,''       } ...
  ,{'Longitudinal_acceleration','G'      ,1       ,'VBox_Longitudinal_acceleration','G'       ,''       } ...
  ,{'Lateral_acceleration'     ,'G'      ,1       ,'VBox_Lateral_acceleration'     ,'G'       ,''       } ...
  ,{'Vel_Quality'              ,'km/h'   ,1       ,'VBox_Vel_Quality'              ,'km/h'    ,''       } ...
  ,{'True_Heading'             ,'degrees',1       ,'VBox_True_Heading'             ,'degrees' ,''       } ...
  ,{'Slip_Angle'               ,'degrees',1       ,'VBox_Slip_Angle'               ,'degrees' ,''       } ...
  ,{'Pitch_Angle'              ,'degrees',1       ,'VBox_Pitch_Angle'              ,'degrees' ,''       } ...
  ,{'Lat_Velocity_kmh'         ,'km/h'   ,1       ,'VBox_Lat_Velocity_kmh'         ,'km/h'    ,''       } ...
  ,{'Yaw_Rate'                 ,'deg/s'  ,1       ,'VBox_Yaw_Rate'                 ,'deg/s'   ,''       } ...
  ,{'Roll_Angle'               ,'degrees',1       ,'VBox_Roll_Angle'               ,'degrees' ,''       } ...
  ,{'Long_Velocity_kmh'        ,'km/h'   ,1       ,'VBox_Long_Velocity_kmh'        ,'km/h'    ,''       } ...
  ,{'Kalman_Filter_Status'     ,''       ,0       ,'VBox_Kalman_Filter_Status'     ,''        ,''       } ...
  ,{'Solution_Type'            ,'1'      ,0       ,'VBox_Solution_Type'            ,'1'       ,''       } ...
  ,{'Slip_COG'                 ,'deg'    ,1       ,'VBox_Slip_COG'                 ,'deg'     ,''       } ...
  };
  Ssig = cell_liste2struct(c);
