function Ssig = CarMakerSigList
%
% Design List of signals from VPU-Can do read from measurement
%
% Ssig(i).name_in      = 'signal name';
% Ssig(i).unit_in      = 'dbc unit';
% Ssig(i).lin_in       = 0/1;
% Ssig(i).name_sign_in = 'signal name for sign';
% Ssig(i).name_out     = 'output signal name';
% Ssig(i).unit_out     = 'output unit';
% Ssig(i).comment      = 'description';
%
% name_in      is name from dbc, could also be used with two and mor names
%              in cell array {'nameold','namenew'}, if their was an change
%              in dbc, use for old measurements
% unit_in      will used if no unit is in dbc for that input signal
% lin_in       =0/1 linearise if to interpolate to a commen time base
% name_sign_in if in dbc-File is a particular signal for sign (how VW
%              uses) exist
% name_out     output name in Matlab
% unit_out     output unit
% comment      description

Ssig = [];

  c =  ...
  {{                                                   'name_in','unit_in' ,'lin_in',                                     'name_out','unit_out',                                                           'comment'} ...
  ,{'Car_v'                                                     ,'m/s'     ,1 ,'Car_v'                                              ,'m/s'     ,'Fahrzeuggeschwindigkeit'} ... 
  ,{'Car_Gen_ay_1'                                              ,'m/s/s'   ,1 ,'Car_Gen_ay_1'                                                     ,'m/s/s'   ,'Fahrzeugquerbeschleunigung'} ... 
  ,{'Car_Gen_ax_1'                                              ,'m/s/s'   ,1 ,'Car_Gen_ax_1'                                                     ,'m/s/s'   ,'Fahrzeugquerbeschleunigung'} ... 
  ,{'Car_YawRate'                                               ,'rad/s'   ,1 ,'Car_YawRate'                                           ,'rad/s'   ,'Fahrzeuggierrate'} ... 
  ,{'Car_SideSlipAngle'                                         ,'rad'     ,1 ,'Car_SideSlipAngle'                                                     ,'rad'     ,'Schwimmwinkel Fahrzeug'} ... 
  ,{'Driver_Gas'                                                ,'%'       ,1 ,'Driver_Gas'                                                      ,'-'       ,'Fahrergaspedalstellung'} ... 
  ,{'Steer_WhlAng'                                              ,'rad'     ,1 ,'Steer_WhlAng'                                        ,'rad'     ,'Lenkradwinkel'} ... 
  ,{'Steer_WhlVel'                                              ,'rad/s'   ,1 ,'Steer_WhlVel'                                       ,'rad/s'   ,'Lenkradwinkel'} ... 
  ,{'Steer_WhlTrq'                                              ,'Nm'      ,1 ,'Steer_WhlTrq'                                              ,'Nm'      ,'Handmoment'} ... 
  ,{'Steer_WhlTrqStatic'                                        ,'Nm'      ,1 ,'Steer_WhlTrqStatic'                                        ,'Nm'      ,'statisches Handmoment aus Zahnstangenkräfte'} ... 
  ,{'Car_Yaw'                                                   ,'rad'     ,1 ,'Car_Yaw'                                                    ,'rad'     ,'Fahrzeuggierwinkel'} ... 
  ,{'Car_C<FL,FR,RL,RR>_rz'                                     ,'rad'     ,1 ,'Car_C<Fl,Fr,Rl,Rr>_rz'                                      ,'rad'     ,'Yaw-winkel (Gier,um z-Achse) Rad im Fahrzeugreferenzsystem (Aufbau) '} ... 
  ,{'Car_WheelSpd_<FL,FR,RL,RR>'                                ,'rad/s'   ,1 ,'OmegaWh<Fl,Fr,Rl,Rr>'                                      ,'rad/s'   ,'Raddrehgeschwindigkeit '} ... 
  ,{'Car_Fz<FL,FR,RL,RR>'                                       ,'N'       ,1 ,'Car_Fz<Fl,Fr,Rl,Rr>'                                         ,'N'       ,'Radaufstandskraft '} ... 
  ,{'Car_LongSlip<FL,FR,RL,RR>'                                 ,'-'       ,1 ,'Car_LongSlip<Fl,Fr,Rl,Rr>'                                     ,'-'       ,'Längsschlupf'} ... 
  ,{'Car_SlipAngle<FL,FR,RL,RR>'                                ,'rad'     ,1 ,'Car_SlipAngle<Fl,Fr,Rl,Rr>'                                      ,'rad'     ,'Schräglaufwinkel'} ... 
  ,{'Car_TurnSlip<FL,FR,RL,RR>'                                 ,'1/m'     ,1 ,'Car_TurnSlip<Fl,Fr,Rl,Rr>'                                        ,'1/m'     ,'Bohrschlupf'} ... 
  ,{'Car_InclinAngle<FL,FR,RL,RR>'                              ,'rad'     ,1 ,'Car_InclinAngle<Fl,Fr,Rl,Rr>'                                      ,'rad'     ,'Bohrschlupf'} ... 
  ,{'Car_Fx<FL,FR,RL,RR>'                                       ,'N'       ,1 ,'Car_Fx<Fl,Fr,Rl,Rr>'                                         ,'N'       ,'Reifenlängskraft '} ... 
  ,{'Car_Fy<FL,FR,RL,RR>'                                       ,'N'       ,1 ,'Car_Fy<Fl,Fr,Rl,Rr>'                                         ,'N'       ,'Reifenquerkraft '} ... 
  ,{'Car_TrqAlign<FL,FR,RL,RR>'                                 ,'Nm'      ,1 ,'Car_TrqAlign<Fl,Fr,Rl,Rr>'                                         ,'Nm'      ,'Reifenrückstellmoment '} ... 
  ,{'Car_C<FL,FR,RL,RR>_Trq2CExt_2_z'                           ,'Nm'      ,1 ,'Car_C<Fl,Fr,Rl,Rr>_Trq2CExt_2_z'                                      ,'Nm'      ,'externes zusätzliches Reifenrückstellmoment '} ... 
  ,{'Car_TrqRoll<FL,FR,RL,RR>'                                  ,'Nm'      ,1 ,'Car_TrqRoll<Fl,Fr,Rl,Rr>'                                         ,'Nm'      ,'Rollreibmoment'} ... 
  ,{'Car_LongAngle<FL,FR,RL,RR>'                                ,'-'       ,1 ,'Car_LongAngle<FL,FR,RL,RR>'                                                ,'rad'     ,'Längsschlupf am Reifen'} ... 
  ,{'Car_SlipAngle<FL,FR,RL,RR>'                                ,'-'       ,1 ,'Car_SlipAngle<FL,FR,RL,RR>'                                                ,'rad'     ,'Querschlupf am Reifen'} ... 
  ,{'Car_Fx<FL,FR,RL,RR>'                                       ,'N'       ,1 ,'Car_Fx<FL,FR,RL,RR>'                                                    ,'N'       ,'Längskraft Reifen'} ... 
  ,{'Car_Fy<FL,FR,RL,RR>'                                       ,'N'       ,1 ,'Car_Fy<FL,FR,RL,RR>'                                                    ,'N'       ,'Querkraft Reifen'} ... 
  ,{'Car_Fz<FL,FR,RL,RR>'                                       ,'N'       ,1 ,'Car_Fz<FL,FR,RL,RR>'                                                    ,'N'       ,'Aufstandskraft Reifen'} ... 
  ,{'Car_TrqAlign<FL,FR,RL,RR>'                                 ,'Nm'      ,1 ,'Car_TrqAlign<FL,FR,RL,RR>'                                                    ,'Nm'       ,'Rückstellmoment Reifen'} ... 
  ,{'Steer_Pfeffer_Mech_Torsbar_Trq_Twist'                      ,'Nm'      ,1 ,'TStWhlSensCarMaker'                                        ,'Nm'      ,'gemessenes Fahrerhandmoment/Torsionsstab'} ... 
  ,{'Steer_Pfeffer_Mech_Torsbar_Trq_Fric'                       ,'Nm'      ,1 ,'Steer_Torsbar_Trq_Fric'                                    ,'Nm'      ,'Reibung Torsionsstab'} ... 
  ,{'Steer_Pfeffer_Mech_Trq_SprDamp'                            ,'Nm'      ,1 ,'Steer_Rack_Trq_SprDamp'                                    ,'Nm'      ,'Feder-Dämpferelement parallel zu Torsionsstab'} ... 
  ,{'Steer_Pfeffer_Mech_Torsbar_Trq_Ang'                        ,'rad'     ,1 ,'Steer_Torsbar_Trq_Ang'                                     ,'rad'     ,'Verdrehwinkel Torsionsstab'} ... 
  ,{'Steer_Pfeffer_Mech_Trq_Pinion'                             ,'Nm'      ,1 ,'Steer_Rack_Trq_Pinion'                                     ,'Nm'      ,'Moment in Zahnritzel'} ... 
  ,{'Steer_AssistFrc'                                           ,'N'       ,1 ,'Steer_assistFrc'                                           ,'N'       ,'AssistenzKraft Zahnstange'} ... 
  ,{'Steer_AssistFrc_Ext'                                       ,'N'       ,1 ,'Steer_assistFrc_Ext'                                       ,'N'       ,'AssistenzKraft Rack extern aus ContiSteer'} ... 
  ,{'Steer_L_Frc'                                               ,'N'       ,1 ,'Steer_L_Frc'                                               ,'N'       ,'Zahnstangengegenkraft links'} ... 
  ,{'Steer_L_Inert'                                             ,'kg'      ,1 ,'Steer_L_Inert'                                             ,'kg'      ,'Zahnstangengegenmasse links'} ... 
  ,{'Steer_L_q'                                                 ,'m'       ,1 ,'Steer_L_q'                                                 ,'m'       ,'Zahnstangenweg links'} ... 
  ,{'Steer_L_qp'                                                ,'m/s'     ,1 ,'Steer_L_qp'                                                ,'m/s'     ,'Zahnstangengeschwindigkeit links'} ... 
  ,{'Steer_L_qpp'                                               ,'m/s/s'   ,1 ,'Steer_L_qpp'                                               ,'m/s/s'   ,'Zahnstangenbeschleunigung links'} ... 
  ,{'Steer_L_iSteer2q'                                          ,'m/rad'   ,1 ,'Steer_L_iSteer2q'                                          ,'m/rad'   ,'Übersetzung Pinion zu Zahnstange links'} ... 
  ,{'Steer_R_Frc'                                               ,'N'       ,1 ,'Steer_R_Frc'                                               ,'N'       ,'Zahnstangengegenkraft links'} ... 
  ,{'Steer_R_Inert'                                             ,'kg'      ,1 ,'Steer_R_Inert'                                             ,'kg'      ,'Zahnstangengegenmasse rechts'} ... 
  ,{'Steer_R_q'                                                 ,'m'       ,1 ,'Steer_R_q'                                                 ,'m'       ,'Zahnstangenweg rechts'} ... 
  ,{'Steer_R_qp'                                                ,'m/s'     ,1 ,'Steer_R_qp'                                                ,'m/s'     ,'Zahnstangengeschwindigkeit rechts'} ... 
  ,{'Steer_R_qpp'                                               ,'m/s/s'   ,1 ,'Steer_R_qpp'                                               ,'m/s/s'   ,'Zahnstangenbeschleunigung rechts'} ... 
  ,{'Steer_R_iSteer2q'                                          ,'m/rad'   ,1 ,'Steer_R_iSteer2q'                                          ,'m/rad'   ,'Übersetzung Pinion zu Zahnstange rechts'} ... 
  ,{'Steer_Pfeffer_Mech_Column_Trq_Fric'                        ,'Nm'      ,1 ,'Steer_Column_Trq_Fric'                                     ,'Nm'      ,'Reibung an der oberen Lenkstange (Column)'} ... 
  ,{'Steer_Pfeffer_Mech_DeltaAng'                               ,'rad'     ,1 ,'Steer_DeltaAng'                                            ,'rad'     ,'delta Winkel zwischen Lenkrad und Zahnritzel (Pinion)'} ... 
  ,{'Steer_Pfeffer_Mech_DeltaAngVel'                            ,'rad/s'   ,1 ,'Steer_DeltaAngVel'                                         ,'rad/s'   ,'delta Winkelgeschwindigkeit zwischen Lenkrad und Zahnritzel (Pinion)'} ... 
  ,{'Steer_Pfeffer_Mech_Rack_Frc_Damp'                          ,'N'       ,1 ,'Steer_Rack_Frc_Damp'                                       ,'N'       ,'Dämpfung Zahnstange'} ... 
  ,{'Steer_Pfeffer_Mech_Rack_Frc_Fric'                          ,'N'       ,1 ,'Steer_Rack_Frc_Fric'                                       ,'N'       ,'Reibung Zahnstange'} ... 
  ,{'RPSensor_RPS0m_x'                                          ,'m'       ,1 ,'xSpur'                                                     ,'m'       ,'x-Position Spur global'} ... 
  ,{'RPSensor_RPS0m_y'                                          ,'m'       ,1 ,'ySpur'                                                     ,'m'       ,'y-Position Spur global'} ... 
  ,{'Car_BdySensor_BSFrontAxle_Pos_0_x'                         ,'m'       ,1 ,'xVehVA'                                                    ,'m'       ,'x-Position Vorderachse global'} ... 
  ,{'Car_BdySensor_BSFrontAxle_Pos_0_y'                         ,'m'       ,1 ,'yVehVA'                                                    ,'m'       ,'y-Position Vorderachse global'} ... 
  ,{'ContiUser_Eps_TStMotReqEps'                                ,'Nm'      ,1       ,'PT_LH2_ALT_Requested_motor_torque'                                              ,'Nm'      ,'angefordertes Motormoment Lenkung'} ... 
  ,{'ContiUser_Eps_TStMotActEps'                                ,'Nm'      ,1       ,'PT_LH2_ALT_Motor_torque'                                              ,'Nm'      ,'aktuelles Motormoment Lenkung'} ... 
  ,{'ContiUser_PrivCAN_VehSpd'                                  ,'m/s'     ,1       ,'vVeh'                                                      ,'m/s'     ,'Fahrzeuggeschwindigkeit'} ... 
  ,{'ContiUser_PrivCAN_VehYawRate_Raw'                          ,'rad/s'   ,1       ,'yawpVeh'                                                   ,'rad/s'   ,'Fahrzeuggierrate CAN Auflösung'} ... 
  ,{'ContiUser_PrivCAN_Gear'                                    ,'-'       ,1       ,'Gear'                                                      ,'-'       ,'eingelegter Gang'} ... 
  ,{'ContiUser_PrivCAN_StW_Angl'                                ,'rad'     ,1       ,'deltaStWhl'                                                ,'rad'     ,'Lenkradwinkel'} ... 
  ,{'ContiUser_PrivCAN_StW_AnglSpd'                             ,'rad/s'   ,1       ,'deltapStWhl'                                               ,'rad/s'   ,'Lenkradwinkel'} ... 
  ,{'ContiUser_PrivCAN_RDU_LenkMoment'                          ,'Nm'      ,1       ,'TStWhlSens'                                                ,'Nm'      ,'gemessenes Fahrerhandmoment/Torsionsstab'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_available'                    ,'-'       ,1       ,'SALaLoIqfm_available'                                      ,'-'       ,'Available Mittenführung'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_c0'                           ,'1/m'     ,1       ,'SALaLoIqfm_c0'                                             ,'1/m'     ,'Kurvenkrümmung Mittenführung'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_c1'                           ,'1/m/m'   ,1       ,'SALaLoIqfm_c1'                                             ,'1/m/m'   ,'Kurvenkrümmungsänderung Mittenführung'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_intervType'                   ,'-'       ,1       ,'SALaLoIqfm_intervType'                                     ,'-'       ,'Intervention Typ Mittenführung bit0: LKAS on'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_dy'                           ,'m'       ,1       ,'SALaLoIqfm_dy'                                             ,'m'       ,'Mittenführung Querabweichung zur Trajektorie vom Fahrzeug ausgesehen '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_psi'                          ,'rad'     ,1       ,'SALaLoIqfm_psi'                                            ,'rad'     ,'Mittenführung Gierwinkel zur Trajektorie vom Fahrzeug ausgesehen'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_projection'                   ,'m'       ,1       ,'SALaLoIqfm_projection'                                     ,'m'       ,'Mittenführung Projektion'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_leftStrength'                 ,'%'       ,1       ,'SALaLoIqfm_leftStrength'                                   ,'%'       ,'Mittenführung Reduzierung links um x % <= 100% '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqfm_rightStrength'                ,'%'       ,1       ,'SALaLoIqfm_rightStrength'                                  ,'%'       ,'Mittenführung Reduzierung rechts um x % <= 100% '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_midDistL'                     ,'m'       ,1       ,'SALaLoIqf1_midDistL'                                       ,'m'       ,'mittlere Regeldistanz links (1. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_maxDistL'                     ,'m'       ,1       ,'SALaLoIqf1_maxDistL'                                       ,'m'       ,'maximale Regeldistanz links (1. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_minDistL'                     ,'m'       ,1       ,'SALaLoIqf1_minDistL'                                       ,'m'       ,'minimale Regeldistanz links (1. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_tqRampDistL'                  ,'m'       ,1       ,'SALaLoIqf1_tqRampDistL'                                    ,'m'       ,'Anstiegsbereich Regeldistanz links (1. Begrenzung)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_availableL'                   ,'-'       ,1       ,'SALaLoIqf1_availableL'                                     ,'-'       ,'linke Spurbegrenzung vorhanden (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_strengthL'                    ,'%'       ,1       ,'SALaLoIqf1_strengthL'                                      ,'%'       ,'Begrenzung Eingriff linke Spurbegrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_intervTypeL'                  ,'-'       ,1       ,'SALaLoIqf1_intervTypeL'                                    ,'-'       ,'Interventionstyp linke Begrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_c0L'                          ,'1/m'     ,1       ,'SALaLoIqf1_c0L'                                            ,'1/m'     ,'Kurvenkrümmung linken Spurbegrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_c1L'                          ,'1/m/m'   ,1       ,'SALaLoIqf1_c1L'                                            ,'1/m/m'   ,'Änderung Kurvenkrümmung linken Spurbegrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_dyL'                          ,'m'       ,1       ,'SALaLoIqf1_dyL'                                            ,'m'       ,'Querabweichung zur linken Spurbegrenzung vom Fahrzeug gesehen (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_psiL'                         ,'rad'     ,1       ,'SALaLoIqf1_psiL'                                           ,'rad'     ,'Gierwinkel zur linken Spurbegrenzung vom Fahrzeug gesehen (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_projectionL'                  ,'m'       ,1       ,'SALaLoIqf1_projectionL'                                    ,'m'       ,'Projektionslänge für Eingriff an linker Begrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_TypeLeft'                     ,'-'       ,1       ,'SALaLoIqf1_TypeLeft'                                       ,'-'       ,'Type Eingriff bit0: LDW, bit1: Intv linker Begrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_midDistR'                     ,'m'       ,1       ,'SALaLoIqf1_midDistR'                                       ,'m'       ,'mittlere Regeldistanz rechts (1. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_maxDistR'                     ,'m'       ,1       ,'SALaLoIqf1_maxDistR'                                       ,'m'       ,'maximale Regeldistanz rechts (1. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_minDistR'                     ,'m'       ,1       ,'SALaLoIqf1_minDistR'                                       ,'m'       ,'minimale Regeldistanz rechts (1. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_tqRampDistR'                  ,'m'       ,1       ,'SALaLoIqf1_tqRampDistR'                                    ,'m'       ,'Anstiegsbereich Regeldistanz rechts (1. Begrenzung)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_availableR'                   ,'-'       ,1       ,'SALaLoIqf1_availableR'                                     ,'-'       ,'rechte Spurbegrenzung vorhanden (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_strengthR'                    ,'%'       ,1       ,'SALaLoIqf1_strengthR'                                      ,'%'       ,'Begrenzung Eingriff rechte Spurbegrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_intervTypeR'                  ,'-'       ,1       ,'SALaLoIqf1_intervTypeR'                                    ,'-'       ,'Interventionstyp rechte Begrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_c0R'                          ,'1/m'     ,1       ,'SALaLoIqf1_c0R'                                            ,'1/m'     ,'Kurvenkrümmung rechten Spurbegrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_c1R'                          ,'1/m/m'   ,1       ,'SALaLoIqf1_c1R'                                            ,'1/m/m'   ,'Änderung Kurvenkrümmung rechten Spurbegrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_dyR'                          ,'m'       ,1       ,'SALaLoIqf1_dyR'                                            ,'m'       ,'Querabweichung zur rechten Spurbegrenzung vom Fahrzeug gesehen (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_psiR'                         ,'rad'     ,1       ,'SALaLoIqf1_psiR'                                           ,'rad'     ,'Gierwinkel zur rechten Spurbegrenzung vom Fahrzeug gesehen (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_projectionR'                  ,'m'       ,1       ,'SALaLoIqf1_projectionR'                                    ,'m'       ,'Projektionslänge für Eingriff an rechter Begrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf1_TypeRight'                    ,'-'       ,1       ,'SALaLoIqf1_TypeRight'                                      ,'-'       ,'Type Eingriff bit0: LDW, bit1: Intv rechter Begrenzung (1. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_midDistL'                     ,'m'       ,1       ,'SALaLoIqf2_midDistL'                                       ,'m'       ,'mittlere Regeldistanz links (2. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_maxDistL'                     ,'m'       ,1       ,'SALaLoIqf2_maxDistL'                                       ,'m'       ,'maximale Regeldistanz links (2. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_minDistL'                     ,'m'       ,1       ,'SALaLoIqf2_minDistL'                                       ,'m'       ,'minimale Regeldistanz links (2. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_tqRampDistL'                  ,'m'       ,1       ,'SALaLoIqf2_tqRampDistL'                                    ,'m'       ,'Anstiegsbereich Regeldistanz links (2. Begrenzung)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_availableL'                   ,'-'       ,1       ,'SALaLoIqf2_availableL'                                     ,'-'       ,'linke Spurbegrenzung vorhanden (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_strengthL'                    ,'%'       ,1       ,'SALaLoIqf2_strengthL'                                      ,'%'       ,'Begrenzung Eingriff linke Spurbegrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_intervTypeL'                  ,'-'       ,1       ,'SALaLoIqf2_intervTypeL'                                    ,'-'       ,'Interventionstyp linke Begrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_c0L'                          ,'1/m'     ,1       ,'SALaLoIqf2_c0L'                                            ,'1/m'     ,'Kurvenkrümmung linken Spurbegrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_c1L'                          ,'1/m/m'   ,1       ,'SALaLoIqf2_c1L'                                            ,'1/m/m'   ,'Änderung Kurvenkrümmung linken Spurbegrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_dyL'                          ,'m'       ,1       ,'SALaLoIqf2_dyL'                                            ,'m'       ,'Querabweichung zur linken Spurbegrenzung vom Fahrzeug gesehen (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_psiL'                         ,'rad'     ,1       ,'SALaLoIqf2_psiL'                                           ,'rad'     ,'Gierwinkel zur linken Spurbegrenzung vom Fahrzeug gesehen (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_projectionL'                  ,'m'       ,1       ,'SALaLoIqf2_projectionL'                                    ,'m'       ,'Projektionslänge für Eingriff an linker Begrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_TypeLeft'                     ,''        ,1       ,'SALaLoIqf2_TypeLeft'                                       ,''        ,'Type Eingriff bit0: LDW, bit1: Intv linker Begrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_midDistR'                     ,'m'       ,1       ,'SALaLoIqf2_midDistR'                                       ,'m'       ,'mittlere Regeldistanz rechts (2. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_maxDistR'                     ,'m'       ,1       ,'SALaLoIqf2_maxDistR'                                       ,'m'       ,'maximale Regeldistanz rechts (2. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_minDistR'                     ,'m'       ,1       ,'SALaLoIqf2_minDistR'                                       ,'m'       ,'minimale Regeldistanz rechts (2. Begrenzung) '} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_tqRampDistR'                  ,'m'       ,1       ,'SALaLoIqf2_tqRampDistR'                                    ,'m'       ,'Anstiegsbereich Regeldistanz rechts (2. Begrenzung)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_availableR'                   ,'-'       ,1       ,'SALaLoIqf2_availableR'                                     ,'-'       ,'rechte Spurbegrenzung vorhanden (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_strengthR'                    ,'%'       ,1       ,'SALaLoIqf2_strengthR'                                      ,'%'       ,'Begrenzung Eingriff rechte Spurbegrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_intervTypeR'                  ,'-'       ,1       ,'SALaLoIqf2_intervTypeR'                                    ,'-'       ,'Interventionstyp rechte Begrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_c0R'                          ,'1/m'     ,1       ,'SALaLoIqf2_c0R'                                            ,'1/m'     ,'Kurvenkrümmung rechten Spurbegrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_c1R'                          ,'1/m/m'   ,1       ,'SALaLoIqf2_c1R'                                            ,'1/m/m'   ,'Änderung Kurvenkrümmung rechten Spurbegrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_dyR'                          ,'m'       ,1       ,'SALaLoIqf2_dyR'                                            ,'m'       ,'Querabweichung zur rechten Spurbegrenzung vom Fahrzeug gesehen (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_psiR'                         ,'rad'     ,1       ,'SALaLoIqf2_psiR'                                           ,'rad'     ,'Gierwinkel zur rechten Spurbegrenzung vom Fahrzeug gesehen (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_projectionR'                  ,'m'       ,1       ,'SALaLoIqf2_projectionR'                                    ,'m'       ,'Projektionslänge für Eingriff an rechter Begrenzung (2. Spur)'} ... 
  ,{'ContiUser_LinQfIn_SALaLoIqf2_TypeRight'                    ,''        ,1       ,'SALaLoIqf2_TypeRight'                                      ,''        ,'Type Eingriff bit0: LDW, bit1: Intv rechter Begrenzung (2. Spur)'} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_Dev2Pth_y'                   ,'m'       ,1       ,'ExtSteerReq_Dev2Pth_y'                                     ,'m'       ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_Dev2Pth_psi'                 ,'rad'     ,1       ,'ExtSteerReq_Dev2Pth_psi'                                   ,'rad'     ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_Dev2Pth_c0'                  ,'1/m'     ,1       ,'ExtSteerReq_Dev2Pth_c0'                                    ,'1/m'     ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_Dev2Pth_quality'             ,'-'       ,1       ,'ExtSteerReq_Dev2Pth_quality'                               ,'-'       ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_Dev2Pth_priority'            ,'-'       ,1       ,'ExtSteerReq_Dev2Pth_priority'                              ,'-'       ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_Dev2Pth_active'              ,'-'       ,1       ,'ExtSteerReq_Dev2Pth_active'                                ,'-'       ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_C0C1_c0'                     ,'1/m'     ,1       ,'ExtSteerReq_C0C1_c0'                                       ,'1/m'     ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_C0C1_c1'                     ,'1/m/m'   ,1       ,'ExtSteerReq_C0C1_c1'                                       ,'1/m/m'   ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_C0C1_quality'                ,'-'       ,1       ,'ExtSteerReq_C0C1_quality'                                  ,'-'       ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_C0C1_priority'               ,'-'       ,1       ,'ExtSteerReq_C0C1_priority'                                 ,'-'       ,''} ... 
  ,{'ContiUser_PrivCAN_ExtSteerReq_C0C1_active'                 ,'-'       ,1       ,'ExtSteerReq_C0C1_active'                                   ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_IQF1_IntvActvStatus'                    ,'-'       ,0       ,'IQF1_IntvActvStatus'                                       ,'-'       ,'Intervention Aktivstatus 0:off,1:L,2:L+VW,3:R,4:R+VW,IQF-Regler'} ... 
  ,{'ContiUser_LinQfOut_IQF1_LdwActvStatus'                     ,'-'       ,0       ,'IQF1_LdwActvStatus'                                        ,'-'       ,'LDW Aktivstatus 0:off,1:L,2:R'} ... 
  ,{'ContiUser_LinQfOut_IQF1_LdwActvIntens'                     ,'-'       ,0       ,'IQF1_LdwActvIntens'                                        ,'-'       ,'LDW Intensität 0:low,1:medium,2:high'} ... 
  ,{'ContiUser_LinQfOut_IQF1_LkasIntvMaxStrength'               ,'%'       ,1       ,'IQF1_LkasIntvMaxStrength'                                  ,'%'       ,'Begrenzung Lkas+Intv'} ... 
  ,{'ContiUser_LinQfOut_IQF1_Curvature'                         ,'1/m'     ,1       ,'IQF1_Curvature'                                            ,'1/m'     ,'Solllenkwinkel IQF-Regler'} ... 
  ,{'ContiUser_LinQfOut_IQF1_LkasIntvDynFac'                    ,'%'       ,1 ,'IQF1_LkasIntvDynFac'                                       ,'%'       ,'Stärke Eingriff IQF-Regler'} ... 
  ,{'ContiUser_LinQfOut_IQF1_LkasActive'                        ,'-'       ,0       ,'IQF1_LkasActive'                                           ,'-'       ,'Lkas-active Flag IQF-Regler'} ... 
  ,{'ContiUser_LinQfOut_IQF2_Status'                            ,'-'       ,0       ,'IQF1_Status'                                               ,'-'       ,'Status IQF-Regler'} ... 
  ,{'ContiUser_LinQfOut_IQF2_IntervTorque'                      ,'Nm'      ,1       ,'IQF2_IntervTorque'                                         ,'Nm'      ,'Solllenkwinkel IQF-Regler'} ... 
  ,{'ContiUser_LinQfOut_IQF2_IntervType'                        ,'-'       ,0 ,'IQF2_IntervType'                                           ,'-'       ,'Interventionstyp 1:Torque,2:RefAngle  IQF-Regler'} ... 
  ,{'ContiUser_LinQfOut_IQF2_GradLim'                           ,'%'       ,0 ,'IQF2_GradLim'                                              ,'%'       ,'Grad der Limitierung beim Einfaden'} ... 
  ,{'ContiUser_LinQfOut_IQF1_LdwStatus'                         ,'-'       ,0 ,'IQF1_LdwStatus'                                            ,'-'       ,'LDW Aktivstatus 0:off,1:L,2:R'} ... 
  ,{'ContiUser_LinQfOut_IQF1_LdwIntens'                         ,'-'       ,0 ,'IQF1_LdwIntens'                                            ,'-'       ,'LDW Intensität 0:low,1:medium,2:high'} ... 
  ,{'ContiUser_LinQfOut_IQF1_RefActivity'                       ,'-'       ,0 ,'IQF1_RefActivity'                                          ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_IQF1_RefAng'                            ,'rad'     ,1       ,'IQF1_RefAng'                                               ,'rad'     ,'Solllenkwinkel IQF-Regler'} ... 
  ,{'ContiUser_LinQfOut_IQF1_RefPriority'                       ,'-'       ,0 ,'IQF1_RefPriority'                                          ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_IQF1_RefQuality'                        ,'-'       ,0 ,'IQF1_RefQuality'                                           ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_IQF1_RefTorque'                         ,'Nm'      ,0 ,'IQF1_RefTorque'                                            ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_IQF1_Status'                            ,'-'       ,0 ,'IQF1_Status'                                               ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_IQF2_Curvature'                         ,'1/m'     ,0 ,'IQF2_Curvature'                                            ,'1/m'     ,''} ... 
  ,{'ContiUser_LinQfOut_IQF2_Failure'                           ,'-'       ,0 ,'IQF2_Failure'                                              ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_IQF2_HandTorque'                        ,'Nm'      ,0 ,'IQF2_HandTorque'                                           ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_IQF2_HandsOffDetect'                    ,'-'       ,0 ,'IQF2_HandsOffDetect'                                       ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_LdwStatus'                      ,'-'       ,1       ,'SIQFCAN_LdwStatus'                                         ,'-'       ,'Ldw Lane departure warning activation status'} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_LdwIntens'                      ,'-'       ,1       ,'SIQFCAN_LdwIntens'                                         ,'-'       ,'Intensity Ldw'} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_Status'                         ,'-'       ,1       ,'SIQFCAN_Status'                                            ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_RefAng'                         ,'deg'     ,1       ,'SIQFCAN_RefAng'                                            ,'rad'     ,'reference control steer wheel angle'} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_RefActivity'                    ,'-'       ,1       ,'SIQFCAN_RefActivity'                                       ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_RefPriority'                    ,'-'       ,1       ,'SIQFCAN_RefPriority'                                       ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_RefQuality'                     ,'-'       ,1       ,'SIQFCAN_RefQuality'                                        ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_RefTorque'                      ,'Nm'      ,1       ,'SIQFCAN_RefTorque'                                         ,'Nm'      ,'reference torque'} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_Curvature'                      ,'1/m'     ,1       ,'SIQFCAN_Curvature'                                         ,'1/m'     ,'curvature'} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_HandsOffDetect'                 ,'-'       ,1       ,'SIQFCAN_HandsOffDetect'                                    ,'-'       ,'0: no hands off detected'} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_HandTorque'                     ,'Nm'      ,1       ,'SIQFCAN_HandTorque'                                        ,'Nm'      ,'estimated hand torque'} ... 
  ,{'ContiUser_LinQfOut_SIQFCAN_Failure'                        ,'-'       ,1       ,'SIQFCAN_Failure'                                           ,'-'       ,'failure'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SALaLoIqf1_switchOnIntvL'          ,'-'       ,1       ,'SIQF_SALaLoIqf1_switchOnIntvL'                             ,'-'       ,'On Intervention left 1. track'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SALaLoIqf1_switchOnIntvR'          ,'-'       ,1       ,'SIQF_SALaLoIqf1_switchOnIntvR'                             ,'-'       ,'On Intervention right 1. track'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SALaLoIqf2_switchOnIntvL'          ,'-'       ,1       ,'SIQF_SALaLoIqf2_switchOnIntvL'                             ,'-'       ,'On Intervention left 2. track'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SALaLoIqf2_switchOnIntvR'          ,'-'       ,1       ,'SIQF_SALaLoIqf2_switchOnIntvR'                             ,'-'       ,'On Intervention right 2. track'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SALaLoIqf1_switchOnLdwL'           ,'-'       ,1       ,'SIQF_SALaLoIqf1_switchOnLdwL'                              ,'-'       ,'On LDW left 1. track'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SALaLoIqf1_switchOnLdwR'           ,'-'       ,1       ,'SIQF_SALaLoIqf1_switchOnLdwR'                              ,'-'       ,'On LDW right 1. track'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SALaLoIqf2_switchOnLdwL'           ,'-'       ,1       ,'SIQF_SALaLoIqf2_switchOnLdwL'                              ,'-'       ,'On LDW left 2. track'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SALaLoIqf2_switchOnLdwR'           ,'-'       ,1       ,'SIQF_SALaLoIqf2_switchOnLdwR'                              ,'-'       ,'On LDW right 2. track'} ... 
  ,{'ContiUser_LinQfOut_SIQF_DrvSteTorEst'                      ,'Nm'      ,1       ,'SIQF_DrvSteTorEst'                                         ,'Nm'      ,'estimated driver torque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_DrvSteFac'                         ,'Nm'      ,1       ,'SIQF_DrvSteFac'                                            ,'Nm'      ,'estimated driver torque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_InertiaTorqueEst'                  ,'Nm'      ,1       ,'SIQF_InertiaTorqueEst'                                     ,'Nm'      ,'estimated inertia steer wheel tporque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_LaneB0Min'                         ,'m'       ,1       ,'SIQF_LaneB0Min'                                            ,'m'       ,'minimal lane width'} ... 
  ,{'ContiUser_LinQfOut_SIQF_LaneB0Max'                         ,'m'       ,1       ,'SIQF_LaneB0Max'                                            ,'m'       ,'maximal lane width'} ... 
  ,{'ContiUser_LinQfOut_SIQF_DistVeh2LaneL'                     ,'m'       ,1       ,'SIQF_DistVeh2LaneL'                                        ,'m'       ,'distance to vehicle left'} ... 
  ,{'ContiUser_LinQfOut_SIQF_DistVeh2LaneR'                     ,'m'       ,1       ,'SIQF_DistVeh2LaneR'                                        ,'m'       ,'distance to vehicle right'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IsVehicleLeftRight'                ,'-'       ,1       ,'SIQF_IsVehicleLeftRight'                                   ,'-'       ,'Intervention with vehicle'} ... 
  ,{'ContiUser_LinQfOut_SIQF_LkasPsi'                           ,'rad'     ,1       ,'SIQF_LkasPsi'                                              ,'rad'     ,'Gierwinkel zur Straße/Linie von der Linie zu  Fahrzeug'} ... 
  ,{'ContiUser_LinQfOut_SIQF_LkasY'                             ,'m'       ,1       ,'SIQF_LkasY'                                                ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_LkasC0'                            ,'1/m'     ,1       ,'SIQF_LkasC0'                                               ,'1/m'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_LkasYLongTerm'                     ,'m'       ,1       ,'SIQF_LkasYLongTerm'                                        ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_CombinedActivation'                ,'-'       ,1       ,'SIQF_CombinedActivation'                                   ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_VehicleDistL'                      ,'m'       ,1       ,'SIQF_VehicleDistL'                                         ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_VehicleDistR'                      ,'m'       ,1       ,'SIQF_VehicleDistR'                                         ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvLineDistL'                     ,'m'       ,1       ,'SIQF_IntvLineDistL'                                        ,'m'       ,'Intervention Distance left auf die geregelt wird'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvLineDistR'                     ,'m'       ,1       ,'SIQF_IntvLineDistR'                                        ,'m'       ,'Intervention Distance right auf die geregelt wird'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvLineDist1L'                    ,'m'       ,1       ,'SIQF_IntvLineDist1L'                                       ,'m'       ,'Intevention Distance left 1. Spur'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvLineDist1R'                    ,'m'       ,1       ,'SIQF_IntvLineDist1R'                                       ,'m'       ,'Intevention Distance right 1. Spur'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvLineDist2L'                    ,'m'       ,1       ,'SIQF_IntvLineDist2L'                                       ,'m'       ,'Intevention Distance left 2. Spur'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvLineDist2R'                    ,'m'       ,1       ,'SIQF_IntvLineDist2R'                                       ,'m'       ,'Intevention Distance right 1. Spur'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntervStrengthL'                   ,'%'       ,1       ,'SIQF_IntervStrengthL'                                      ,'%'       ,'Intevention Stärke'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntervStrengthR'                   ,'%'       ,1       ,'SIQF_IntervStrengthR'                                      ,'%'       ,'Intevention Stärke'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SwaFilt'                           ,'rad'     ,1       ,'SIQF_SwaFilt'                                              ,'rad'     ,'filtered steer wheel angle'} ... 
  ,{'ContiUser_LinQfOut_SIQF_DSwaFilt'                          ,'rad/s'   ,1       ,'SIQF_DSwaFilt'                                             ,'rad/s'   ,'filtered steer wheel angle velocity'} ... 
  ,{'ContiUser_LinQfOut_SIQF_D2SwaFilt'                         ,'rad/s/s' ,1       ,'SIQF_D2SwaFilt'                                            ,'rad/s/s' ,'filtered steer wheel angle acceleration'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvDampTorState'                  ,'-'       ,1       ,'SIQF_IntvDampTorState'                                     ,'-'       ,'status of damping torque for intervention'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvDampTor'                       ,'Nm'      ,1       ,'SIQF_IntvDampTor'                                          ,'Nm'      ,'damping torque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvTorL'                          ,'Nm'      ,1       ,'SIQF_IntvTorL'                                             ,'Nm'      ,'virtual wall Inervention Torque Left based on MaxTorque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvTorR'                          ,'Nm'      ,1       ,'SIQF_IntvTorR'                                             ,'Nm'      ,'virtual wall Inervention Torque right based on MaxTorque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvDSwaDampThresh'                ,'rad/s'   ,1       ,'SIQF_IntvDSwaDampThresh'                                   ,'rad/s'   ,'Damping threshold to start damping torque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvD2SwaDampThresh'               ,'rad/s/s' ,1       ,'SIQF_IntvD2SwaDampThresh'                                  ,'rad/s/s' ,'Damping threshold (accel) to start damping torque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_DY1Left'                           ,'m'       ,1       ,'SIQF_DY1Left'                                              ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DY2Left'                           ,'m'       ,1       ,'SIQF_DY2Left'                                              ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DY3Left'                           ,'m'       ,1       ,'SIQF_DY3Left'                                              ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DY4Left'                           ,'m'       ,1       ,'SIQF_DY4Left'                                              ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DY1Right'                          ,'m'       ,1       ,'SIQF_DY1Right'                                             ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DY2Right'                          ,'m'       ,1       ,'SIQF_DY2Right'                                             ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DY3Right'                          ,'m'       ,1       ,'SIQF_DY3Right'                                             ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DY4Right'                          ,'m'       ,1       ,'SIQF_DY4Right'                                             ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvTorque'                        ,'Nm'      ,1       ,'SIQF_IntvTorque'                                           ,'Nm'      ,'Interventiontorque'} ... 
  ,{'ContiUser_LinQfOut_SIQF_DeltaY'                            ,'m'       ,1       ,'SIQF_DeltaY'                                               ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DeltaYDot'                         ,'m/s'     ,1       ,'SIQF_DeltaYDot'                                            ,'m/s'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_YawAngleAct'                       ,'rad'     ,1       ,'SIQF_YawAngleAct'                                          ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_YawAngleReq'                       ,'rad'     ,1       ,'SIQF_YawAngleReq'                                          ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_YawAngleReqPPart'                  ,'rad'     ,1       ,'SIQF_YawAngleReqPPart'                                     ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_YawAngleReqP2Part'                 ,'rad'     ,1       ,'SIQF_YawAngleReqP2Part'                                    ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_YawAngleReqDPart'                  ,'rad'     ,1       ,'SIQF_YawAngleReqDPart'                                     ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_YawAngleReqIPart'                  ,'rad'     ,1       ,'SIQF_YawAngleReqIPart'                                     ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_DeltaYawAngle'                     ,'rad'     ,1       ,'SIQF_DeltaYawAngle'                                        ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleReqPPart'                ,'rad'     ,1       ,'SIQF_SteerAngleReqPPart'                                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleReqDPart'                ,'rad'     ,1       ,'SIQF_SteerAngleReqDPart'                                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleReqIPart'                ,'rad'     ,1       ,'SIQF_SteerAngleReqIPart'                                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleCtrl'                    ,'rad'     ,1       ,'SIQF_SteerAngleCtrl'                                       ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleLongTerm'                ,'rad'     ,1       ,'SIQF_SteerAngleLongTerm'                                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleAdd'                     ,'rad'     ,1       ,'SIQF_SteerAngleAdd'                                        ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleReqLookAhead'            ,'rad'     ,1       ,'SIQF_SteerAngleReqLookAhead'                               ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerWheelAngleReq'                ,'rad'     ,1       ,'SIQF_SteerWheelAngleReq'                                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_HAPS_SteerWhAngleReq_C0'           ,'rad'     ,1       ,'SIQF_HAPS_SteerWhAngleReq_C0'                              ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_HAPS_SteerWhAngleReq_yd'           ,'rad'     ,1       ,'SIQF_HAPS_SteerWhAngleReq_yd'                              ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_HAPS_SteerWhAngleReq_psi'          ,'rad'     ,1       ,'SIQF_HAPS_SteerWhAngleReq_psi'                             ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleRefValue'   ,'rad'     ,1       ,'SIQF_Statespace_SteerWhAngleRefValue'                      ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_YawRateRefValue'        ,'rad/s'   ,1       ,'SIQF_Statespace_YawRateRefValue'                           ,'rad/s'   ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqFeedForward','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqFeedForward'                ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControl' ,'rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControl'                    ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqLongTerm','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqLongTerm'                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReq'        ,'rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReq'                           ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_C0delayed'              ,'1/m'     ,1       ,'SIQF_Statespace_C0delayed'                                 ,'1/m'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControlSwa','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControlSwa'                 ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControlYawp','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControlYawp'                ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControlPsi','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControlPsi'                 ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControlY','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControlY'                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_YawRateRefValue'              ,'rad/s'   ,1       ,'SIQF_C0C1_YawRateRefValue'                                 ,'rad/s'   ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_YawRateActValue'              ,'rad/s'   ,1       ,'SIQF_C0C1_YawRateActValue'                                 ,'rad/s'   ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_DeltaStWhRefValue'            ,'rad'     ,1       ,'SIQF_C0C1_DeltaStWhRefValue'                               ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_CurvatureRefValue'            ,'1/m'     ,1       ,'SIQF_C0C1_CurvatureRefValue'                               ,'1/m'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqFeedForward'   ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqFeedForward'                      ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqControl'       ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqControl'                          ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReq'              ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReq'                                 ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqFilt'          ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqFilt'                             ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqControlYawp'   ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqControlYawp'                      ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqControlYawpDelay','rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqControlYawpDelay'                 ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqControlDeltaStWh','rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqControlDeltaStWh'                 ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_StWhAngReqC0C1'                    ,'rad'     ,1       ,'SIQF_StWhAngReqC0C1'                                       ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_Yaw_int'                      ,'rad'     ,1       ,'SIQF_C0C1_Yaw_int'                                         ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvSteWheAngL'                    ,'rad'     ,1       ,'SIQF_IntvSteWheAngL'                                       ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvSteWheAngR'                    ,'rad'     ,1       ,'SIQF_IntvSteWheAngR'                                       ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvSteWheAngFiltL'                ,'rad'     ,1       ,'SIQF_IntvSteWheAngFiltL'                                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvSteWheAngVelFiltL'             ,'rad/s'   ,1       ,'SIQF_IntvSteWheAngVelFiltL'                                ,'rad/s'   ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvSteWheAngFiltR'                ,'rad'     ,1       ,'SIQF_IntvSteWheAngFiltR'                                   ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvSteWheAngVelFiltR'             ,'rad/s'   ,1       ,'SIQF_IntvSteWheAngVelFiltR'                                ,'rad/s'   ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4SteWhAngDyL'               ,'rad'     ,1       ,'SIQF_IqfCtrl4SteWhAngDyL'                                  ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4SteWhAngPsiL'              ,'rad'     ,1       ,'SIQF_IqfCtrl4SteWhAngPsiL'                                 ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4SteWhAngC0L'               ,'rad'     ,1       ,'SIQF_IqfCtrl4SteWhAngC0L'                                  ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4SteWhAngReqT2TL'           ,'rad'     ,1       ,'SIQF_IqfCtrl4SteWhAngReqT2TL'                              ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4SteWhAngDyR'               ,'rad'     ,1       ,'SIQF_IqfCtrl4SteWhAngDyR'                                  ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4SteWhAngPsiR'              ,'rad'     ,1       ,'SIQF_IqfCtrl4SteWhAngPsiR'                                 ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4SteWhAngC0R'               ,'rad'     ,1       ,'SIQF_IqfCtrl4SteWhAngC0R'                                  ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4SteWhAngReqT2TR'           ,'rad'     ,1       ,'SIQF_IqfCtrl4SteWhAngReqT2TR'                              ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PTorL'                     ,'Nm'      ,1       ,'SIQF_IqfCtrl4PTorL'                                        ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4DTorL'                     ,'Nm'      ,1       ,'SIQF_IqfCtrl4DTorL'                                        ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4ITorL'                     ,'Nm'      ,1       ,'SIQF_IqfCtrl4ITorL'                                        ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4FFTorL'                    ,'Nm'      ,1       ,'SIQF_IqfCtrl4FFTorL'                                       ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PTorR'                     ,'Nm'      ,1       ,'SIQF_IqfCtrl4PTorR'                                        ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4DTorR'                     ,'Nm'      ,1       ,'SIQF_IqfCtrl4DTorR'                                        ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4ITorR'                     ,'Nm'      ,1       ,'SIQF_IqfCtrl4ITorR'                                        ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4FFTorR'                    ,'Nm'      ,1       ,'SIQF_IqfCtrl4FFTorR'                                       ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PGainL'                    ,'Nm/rad'  ,1       ,'SIQF_IqfCtrl4PGainL'                                       ,'Nm/rad'  ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4DGainL'                    ,'Nm*s/rad',1       ,'SIQF_IqfCtrl4DGainL'                                       ,'Nm*s/rad',''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4IGainL'                    ,'Nm/rad/s',1       ,'SIQF_IqfCtrl4IGainL'                                       ,'Nm/rad/s',''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4FFFacL'                    ,'-'       ,1       ,'SIQF_IqfCtrl4FFFacL'                                       ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PGainR'                    ,'Nm/rad'  ,1       ,'SIQF_IqfCtrl4PGainR'                                       ,'Nm/rad'  ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4DGainR'                    ,'Nm*s/rad',1       ,'SIQF_IqfCtrl4DGainR'                                       ,'Nm*s/rad',''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4IGainR'                    ,'Nm/rad/s',1       ,'SIQF_IqfCtrl4IGainR'                                       ,'Nm/rad/s',''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4FFFacR'                    ,'-'       ,1       ,'SIQF_IqfCtrl4FFFacR'                                       ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PsiL'                      ,'rad'     ,1       ,'SIQF_IqfCtrl4PsiL'                                         ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PsiFiltL'                  ,'rad'     ,1       ,'SIQF_IqfCtrl4PsiFiltL'                                     ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4DPsiFiltL'                 ,'rad/s'   ,1       ,'SIQF_IqfCtrl4DPsiFiltL'                                    ,'rad/s'   ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PsiModL'                   ,'rad'     ,1       ,'SIQF_IqfCtrl4PsiModL'                                      ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PsiR'                      ,'rad'     ,1       ,'SIQF_IqfCtrl4PsiR'                                         ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PsiFiltR'                  ,'rad'     ,1       ,'SIQF_IqfCtrl4PsiFiltR'                                     ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4DPsiFiltR'                 ,'rad/s'   ,1       ,'SIQF_IqfCtrl4DPsiFiltR'                                    ,'rad/s'   ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4PsiModR'                   ,'rad'     ,1       ,'SIQF_IqfCtrl4PsiModR'                                      ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4IntvStateL'                ,'-'       ,1       ,'SIQF_IqfCtrl4IntvStateL'                                   ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4IntvDrvTorL'               ,'Nm'      ,1       ,'SIQF_IqfCtrl4IntvDrvTorL'                                  ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4IntvDrvTorAwayFacL'        ,'-'       ,1       ,'SIQF_IqfCtrl4IntvDrvTorAwayFacL'                           ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4IntvStateR'                ,'-'       ,1       ,'SIQF_IqfCtrl4IntvStateR'                                   ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4IntvDrvTorR'               ,'Nm'      ,1       ,'SIQF_IqfCtrl4IntvDrvTorR'                                  ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IqfCtrl4IntvDrvTorAwayFacR'        ,'-'       ,1       ,'SIQF_IqfCtrl4IntvDrvTorAwayFacR'                           ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Time2TouchL'                       ,'s'       ,1       ,'SIQF_Time2TouchL'                                          ,'s'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_Time2TouchR'                       ,'s'       ,1       ,'SIQF_Time2TouchR'                                          ,'s'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvTorVWLim1L'                    ,'m'       ,1       ,'SIQF_IntvTorVWLim1L'                                       ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvTorVWLim2L'                    ,'m'       ,1       ,'SIQF_IntvTorVWLim2L'                                       ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvTorVWLim1R'                    ,'m'       ,1       ,'SIQF_IntvTorVWLim1R'                                       ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvTorVWLim2R'                    ,'m'       ,1       ,'SIQF_IntvTorVWLim2R'                                       ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_EstHandTor'                        ,'Nm'      ,1       ,'SIQF_EstHandTor'                                           ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_HandsOffDetect'                    ,'-'       ,1       ,'SIQF_HandsOffDetect'                                       ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_EstDSwa'                           ,'rad/s'   ,1       ,'SIQF_EstDSwa'                                              ,'rad/s'   ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_EstHandTorCounter'                 ,'-'       ,1       ,'SIQF_EstHandTorCounter'                                    ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_HandsOffCounterLimit'              ,'-'       ,1       ,'SIQF_HandsOffCounterLimit'                                 ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_FiltDrvSteTor'                     ,'Nm'      ,1       ,'SIQF_FiltDrvSteTor'                                        ,'Nm'      ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_EstHandDTor'                       ,'Nm/s'    ,1       ,'SIQF_EstHandDTor'                                          ,'Nm/s'    ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_StWhAngReqLkas'                    ,'rad'     ,1       ,'SIQF_StWhAngReqLkas'                                       ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvRefAngL'                       ,'rad'     ,1       ,'SIQF_IntvRefAngL'                                          ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvRefAngR'                       ,'rad'     ,1       ,'SIQF_IntvRefAngR'                                          ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerWhAngleReq'                   ,'rad'     ,1       ,'SIQF_SteerWhAngleReq'                                      ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_LimitLaneY'                        ,'m'       ,1       ,'SIQF_LimitLaneY'                                           ,'m'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_LimitLanePsi'                      ,'rad'     ,1       ,'SIQF_LimitLanePsi'                                         ,'rad'     ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_LdwActive'                         ,'-'       ,1       ,'SIQF_LdwActive'                                            ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_LdwSwitch'                         ,'-'       ,1       ,'SIQF_LdwSwitch'                                            ,'-'       ,''} ... 
  ,{'ContiUser_LinQfOut_SIQF_IntvSwitch'                        ,'-'       ,1       ,'SIQF_IntvSwitch'                                           ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_IPAS_Soll_Lenkmoment'                  ,'Nm'      ,0 ,'IPAS_Soll_Lenkmoment'                                      ,'Nm'      ,'Solllenkmoment IPAS'} ... 
  ,{'ContiUser_SteerCtrl_IPAS_ACTIVE'                           ,'-'       ,0 ,'IPAS_ACTIVE'                                               ,'-'       ,'IPAS active'} ... 
  ,{'SteerCtrl_IPAS_Debug'                                      ,'-'       ,0 ,'IPAS_Debug'                                                ,'-'       ,'Debug-Größe'} ... 
  ,{'ContiUser_ArbiDev2Path_xS'                                 ,'m'       ,1       ,'XSPath'                                                    ,'m'       ,'x-Position des zu errechnetem Schnittpunkt'} ... 
  ,{'ContiUser_ArbiDev2Path_yS'                                 ,'m'       ,1       ,'YSPath'                                                    ,'m'       ,'y-Position des zu errechnetem Schnittpunkt'} ... 
  ,{'ContiUser_ArbiDev2Path_alphaS'                             ,'rad'     ,1       ,'alphaSPath'                                                ,'rad'     ,'Winkel entalg Pfad im Schnittpunkt'} ... 
  ,{'ContiUser_ArbiDev2Path_c0S'                                ,'1/m'     ,1       ,'C0SPath'                                                   ,'1/m'     ,'Krümmung entlang Pfad im Schnittpunkt'} ... 
  ,{'ContiUser_ArbiDev2Path_c1S'                                ,'1/m/m'   ,1       ,'C1SPath'                                                   ,'1/m/m'   ,'Winkel entlang Pfad im Schnittpunkt'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SwaFiltFast'                       ,'rad'     ,1       ,'SIQF_SwaFiltFast'                                          ,'rad'     ,'Lenkwinkel leicht gefiltert'} ... 
  ,{'ContiUser_LinQfOut_SIQF_YawAngleAct'                       ,'rad'     ,1       ,'SIQF_YawAngleAct'                                          ,'rad'     ,'aktueller Psi-Winkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_YawAngleReq'                       ,'rad'     ,1       ,'SIQF_YawAngleReq'                                          ,'rad'     ,'Soll Psi-Winkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleReqLookAhead'            ,'rad'     ,1       ,'SIQF_SteerAngleReqLookAhead'                               ,'rad'     ,'Vorsteuerwinkel Kaskadebregler'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleCtrl'                    ,'rad'     ,1       ,'SIQF_SteerAngleCtrl'                                       ,'rad'     ,'Reglerwinkel Kaskadenregler'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerAngleLongTerm'                ,'rad'     ,1       ,'SIQF_SteerAngleLongTerm'                                   ,'rad'     ,'Long Term Solllenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SteerWheelAngleReq'                ,'rad'     ,1       ,'SIQF_SteerWheelAngleReq'                                   ,'rad'     ,'Gesamtsolllenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_SwaFilt'                           ,'rad'     ,1       ,'SIQF_SwaFilt'                                              ,'rad'     ,'gefilteter Lenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_LkasPsi'                           ,'rad'     ,1       ,'SIQF_LkasPsi'                                              ,'rad'     ,'gefilteter relativer Gierwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_LkasY'                             ,'m'       ,1       ,'SIQF_LkasY'                                                ,'m'       ,'gefilteter Abstand zur Mitte'} ... 
  ,{'ContiUser_LinQfOut_SIQF_LkasC0'                            ,'1/m'     ,1       ,'SIQF_LkasC0'                                               ,'1/m'     ,'aktuelle Kurvenkrümmung'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_YawRateRefValue'        ,'rad/s'   ,1       ,'SIQF_Statespace_YawRateRefValue'                           ,'rad/s'   ,'gefilteter relativer Gierwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_C0delayed'              ,'1/m'     ,1       ,'SIQF_Statespace_C0delayed'                                 ,'1/m'     ,'verzögerte Kurvenkrümmung'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControlSwa','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControlSwa'                 ,'rad'     ,'Lenkwinkelregelanteil Lenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControlYawp','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControlYawp'                ,'rad'     ,'Lenkwinkelregelanteil Gierwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControlPsi','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControlPsi'                 ,'rad'     ,'Lenkwinkelregelanteil Lenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControlY','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControlY'                   ,'rad'     ,'Lenkwinkelregelanteil Mittenabstand'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqFeedForward','rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqFeedForward'                ,'rad'     ,'Vorsteuerlenkwinkel Statespace'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReqControl' ,'rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReqControl'                    ,'rad'     ,'geregelter Solllenkwinkel Statespace'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReq'        ,'rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReq'                           ,'rad'     ,'geforderter Solllenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleRefValue'   ,'rad'     ,1       ,'SIQF_Statespace_SteerWhAngleRefValue'                      ,'rad'     ,'Lenkwinkel Referenzwert zur Bildung der Differenz'} ... 
  ,{'ContiUser_LinQfOut_SIQF_Statespace_SteerWhAngleReq'        ,'rad'     ,1       ,'SIQF_Statespace_SteerWhAngleReq'                           ,'rad'     ,'geforderter Solllenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_ESA_State'                    ,'-'       ,1       ,'SIQF_C0C1_ESA_State'                                       ,'-'       ,'C0C1-Regler: Zustand ESA: 0:start,1:firstleft,2:firstright,3:secondcurve,4:ahead_first,5:yaw_correct,6:ahead'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_CurvatureRefValue'            ,'1/m'     ,1       ,'SIQF_C0C1_CurvatureRefValue'                               ,'1/m'     ,'C0C1-Regler: Kurvensollwert'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_YawRateRefValue'              ,'rad/s'   ,1       ,'SIQF_C0C1_YawRateRefValue'                                 ,'rad/s'   ,'C0C1-Regler: Giersollrate'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_DeltaStWhRefValue'            ,'rad'     ,1       ,'SIQF_C0C1_DeltaStWhRefValue'                               ,'rad'     ,'C0C1-Regler: Giersollrate'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqFeedForward'   ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqFeedForward'                      ,'rad'     ,'C0C1-Regler: feed forward solllenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqControl'       ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqControl'                          ,'rad'     ,'C0C1-Regler: Ctrl-Solllenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReq'              ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReq'                                 ,'rad'     ,'C0C1: ungefilterter Solllenkwinkel'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqFilt'          ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqFilt'                             ,'rad'     ,'C0C1: Solllenkwinkel gefiltert'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqControlYawp'   ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqControlYawp'                      ,'rad'     ,'C0C1: Lenkwinkel anteil aus Gierrate'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqControlYaw'    ,'rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqControlYaw'                       ,'rad'     ,'C0C1: Lenkwinkel anteil aus Gierwinkelkorrektur am  ende'} ... 
  ,{'ContiUser_LinQfOut_SIQF_C0C1_SteerWhAngleReqControlDeltaStWh','rad'     ,1       ,'SIQF_C0C1_SteerWhAngleReqControlDeltaStWh'                 ,'rad'     ,'C0C1: Lenkwinkel anteil aus Lenkwinkel'} ... 
  ,{'ContiUser_SteerCtrl_SSTCCAN_IPAS_Soll_Lenkmoment'          ,'Nm'      ,1       ,'SSTCCAN_IPAS_Soll_Lenkmoment'                              ,'Nm'      ,'Solllenkmoment'} ... 
  ,{'ContiUser_SteerCtrl_SSTCCAN_IPAS_ACTIVE'                   ,'-'       ,1       ,'SSTCCAN_IPAS_ACTIVE'                                       ,'-'       ,'Ipas Active'} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaRequest_iArb'                  ,'-'       ,1       ,'SSTC_SwaRequest_iArb'                                      ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaRequest_Active'                ,'-'       ,1       ,'SSTC_SwaRequest_Active'                                    ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaRequest_Priority'              ,'-'       ,1       ,'SSTC_SwaRequest_Priority'                                  ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaRequest_Quality'               ,'-'       ,1       ,'SSTC_SwaRequest_Quality'                                   ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaRequest_SwaRef'                ,'-'       ,1       ,'SSTC_SwaRequest_SwaRef'                                    ,'deg'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaRequest_VirtWall_L'            ,'-'       ,1       ,'SSTC_SwaRequest_VirtWall_L'                                ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaRequest_VirtWall_R'            ,'-'       ,1       ,'SSTC_SwaRequest_VirtWall_R'                                ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaRefFilt'                       ,'deg'     ,1       ,'SSTC_SwaRefFilt'                                           ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DSwaRefFiltFast'                  ,'deg/s'   ,1       ,'SSTC_DSwaRefFiltFast'                                      ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_SwaFilt'                          ,'deg'     ,1       ,'SSTC_SwaFilt'                                              ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DSwaFilt'                         ,'deg/s'   ,1       ,'SSTC_DSwaFilt'                                             ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_D2SwaFilt'                        ,'deg/s/s' ,1       ,'SSTC_D2SwaFilt'                                            ,'rad/s/s' ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DSwaFiltFast'                     ,'deg/s'   ,1       ,'SSTC_DSwaFiltFast'                                         ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DeltaSwa'                         ,'deg'     ,1       ,'SSTC_DeltaSwa'                                             ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DeltaDSwa'                        ,'deg/s'   ,1       ,'SSTC_DeltaDSwa'                                            ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DeltaD2Swa'                       ,'deg/s/s' ,1       ,'SSTC_DeltaD2Swa'                                           ,'rad/s/s' ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DrvSteTorFac'                     ,'-'       ,1       ,'SSTC_DrvSteTorFac'                                         ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DrvSteOvertakeIntv'               ,'-'       ,1       ,'SSTC_DrvSteOvertakeIntv'                                   ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_SwaRef'                    ,'deg'     ,1       ,'SSTC_Cntrl1_SwaRef'                                        ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_SwaAct'                    ,'deg'     ,1       ,'SSTC_Cntrl1_SwaAct'                                        ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DeltaSwa'                  ,'deg'     ,1       ,'SSTC_Cntrl1_DeltaSwa'                                      ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DSwaCntrl'                 ,'deg/s'   ,1       ,'SSTC_Cntrl1_DSwaCntrl'                                     ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DSwaCntrlRef'              ,'deg/s'   ,1       ,'SSTC_Cntrl1_DSwaCntrlRef'                                  ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DSwaRef'                   ,'deg/s'   ,1       ,'SSTC_Cntrl1_DSwaRef'                                       ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DSwaAct'                   ,'deg/s'   ,1       ,'SSTC_Cntrl1_DSwaAct'                                       ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DeltaDSwa'                 ,'deg/s'   ,1       ,'SSTC_Cntrl1_DeltaDSwa'                                     ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DeltaDSwaFilt'             ,'deg/s'   ,1       ,'SSTC_Cntrl1_DeltaDSwaFilt'                                 ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DeltaDSwaDot'              ,'deg/s/s' ,1       ,'SSTC_Cntrl1_DeltaDSwaDot'                                  ,'rad/s/s' ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_DeltaDSwaSum'              ,'deg'     ,1       ,'SSTC_Cntrl1_DeltaDSwaSum'                                  ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_TorqueP'                   ,'Nm'      ,1       ,'SSTC_Cntrl1_TorqueP'                                       ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_TorqueI'                   ,'Nm'      ,1       ,'SSTC_Cntrl1_TorqueI'                                       ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_TorqueD'                   ,'Nm'      ,1       ,'SSTC_Cntrl1_TorqueD'                                       ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_TorquePDir'                ,'Nm'      ,1       ,'SSTC_Cntrl1_TorquePDir'                                    ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_TorqueRaw'                 ,'Nm'      ,1       ,'SSTC_Cntrl1_TorqueRaw'                                     ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_ForwardTorqueSwaReqRaw'    ,'Nm'      ,1       ,'SSTC_Cntrl1_ForwardTorqueSwaReqRaw'                        ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_LowFac'                    ,'-'       ,1       ,'SSTC_Cntrl1_LowFac'                                        ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_TorSwaRefMaxFFCtrl'        ,'Nm'      ,1       ,'SSTC_Cntrl1_TorSwaRefMaxFFCtrl'                            ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_TorqueRefSwaReqRaw'        ,'Nm'      ,1       ,'SSTC_Cntrl1_TorqueRefSwaReqRaw'                            ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl1_MaxGrad'                   ,'Nm/s'    ,1       ,'SSTC_Cntrl1_MaxGrad'                                       ,'Nm/s'    ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_DeltaSwa'                  ,'deg'     ,1       ,'SSTC_Cntrl2_DeltaSwa'                                      ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_DeltaSwaDot'               ,'deg/s'   ,1       ,'SSTC_Cntrl2_DeltaSwaDot'                                   ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_DeltaDSwa'                 ,'deg/s'   ,1       ,'SSTC_Cntrl2_DeltaDSwa'                                     ,'rad/s'   ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_DeltaD2Swa'                ,'deg/s/s' ,1       ,'SSTC_Cntrl2_DeltaD2Swa'                                    ,'rad/s/s' ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_DeltaDSwaSum'              ,'deg'     ,1       ,'SSTC_Cntrl2_DeltaDSwaSum'                                  ,'rad'     ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorqueP'                   ,'Nm'      ,1       ,'SSTC_Cntrl2_TorqueP'                                       ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorqueI'                   ,'Nm'      ,1       ,'SSTC_Cntrl2_TorqueI'                                       ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorqueD1'                  ,'Nm'      ,1       ,'SSTC_Cntrl2_TorqueD1'                                      ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorqueD2'                  ,'Nm'      ,1       ,'SSTC_Cntrl2_TorqueD2'                                      ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorqueDD'                  ,'Nm'      ,1       ,'SSTC_Cntrl2_TorqueDD'                                      ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorqueDRef'                ,'Nm'      ,1       ,'SSTC_Cntrl2_TorqueDRef'                                    ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorqueRaw'                 ,'Nm'      ,1       ,'SSTC_Cntrl2_TorqueRaw'                                     ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorqueSwaReqRaw'           ,'Nm'      ,1       ,'SSTC_Cntrl2_TorqueSwaReqRaw'                               ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorSwaRefMaxFFCtrl'        ,'Nm'      ,1       ,'SSTC_Cntrl2_TorSwaRefMaxFFCtrl'                            ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_FFMaxGrad'                 ,'Nm/s'    ,1       ,'SSTC_Cntrl2_FFMaxGrad'                                     ,'Nm/s'    ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorSwaRefMaxTotal'         ,'Nm'      ,1       ,'SSTC_Cntrl2_TorSwaRefMaxTotal'                             ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Cntrl2_TorSwaRefAdd'              ,'Nm'      ,1       ,'SSTC_Cntrl2_TorSwaRefAdd'                                  ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_TorqueRefSwaReq'                  ,'Nm'      ,1       ,'SSTC_TorqueRefSwaReq'                                      ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_ForwardTorSwaReq'                 ,'Nm'      ,1       ,'SSTC_ForwardTorSwaReq'                                     ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_CntrlTorSwaReq'                   ,'Nm'      ,1       ,'SSTC_CntrlTorSwaReq'                                       ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_LongTermTorSwaReq'                ,'Nm'      ,1       ,'SSTC_LongTermTorSwaReq'                                    ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DrvTorSwaReq'                     ,'Nm'      ,1       ,'SSTC_DrvTorSwaReq'                                         ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_DampTor'                          ,'Nm'      ,1       ,'SSTC_DampTor'                                              ,'Nm'      ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_RampTorqueGradient'               ,'Nm/s'    ,1       ,'SSTC_RampTorqueGradient'                                   ,'Nm/s'    ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_Active'                           ,'-'       ,1       ,'SSTC_Active'                                               ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_ActiveLdw'                        ,'-'       ,1       ,'SSTC_ActiveLdw'                                            ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_TorRequest_iArb'                  ,'-'       ,1       ,'SSTC_TorRequest_iArb'                                      ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_TorRequest_Active'                ,'-'       ,1       ,'SSTC_TorRequest_Active'                                    ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_TorRequest_Priority'              ,'-'       ,1       ,'SSTC_TorRequest_Priority'                                  ,'-'       ,''} ... 
  ,{'ContiUser_SteerCtrl_SSTC_TorRequest_Torque'                ,'Nm'      ,1       ,'SSTC_TorRequest_Torque'                                    ,'Nm'      ,''} ... 
  ,{'ContiUser_ArbiDev2Path_xEgoFA'                             ,'m'       ,1       ,'Tra_1_XPosEgo'                                             ,'m'       ,'x-Koordinate Ego-Position'} ... 
  ,{'ContiUser_ArbiDev2Path_yEgoFA'                             ,'m'       ,1       ,'Tra_1_YPosEgo'                                             ,'m'       ,'y-Koordinate Ego-Position'} ... 
  ,{'ContiUser_ArbiDev2Path_yawEgo'                             ,'rad'     ,1       ,'Tra_1_YawPosEgo'                                           ,'rad'     ,'Yaw-winkel (Gier,um x-Achse) Rad im Fahrzeugreferenzsystem (Aufbau) hinten rechts'} ... 
  };


  Ssig = cell_liste2struct(c);

%   iSig = 0;
%   for i = 1:length(C_Sig)
%     iSig = iSig + 1;
%     Ssig(iSig).name_in      = C_Sig{i}{1};
%     Ssig(iSig).unit_in      = C_Sig{i}{2};
%     Ssig(iSig).lin_in       = C_Sig{i}{3};
%     Ssig(iSig).name_sign_in = '';
%     Ssig(iSig).name_out     = C_Sig{i}{4};
%     Ssig(iSig).unit_out     = C_Sig{i}{5};
%     Ssig(iSig).comment      = C_Sig{i}{6};
%   end
end