function   [c_siglist_in,c_siglist_out] = cg_change_signal_name_list
  % Signalliste mit den bestehenden Namen
  %{name_in                  , unit_in            , name_new}
  c_siglist_in = ...
  {{'VehAccel_Y'                  , 'm/s/s'            , 'ayVehCOG'} ...              % VPU-CAN
  ,{'VehAccel_X'                  , 'm/s/s'            , 'axVehCOG'} ...
  ,{'Veh_Accel_X_Est'             , 'm/s/s'            , 'axVehCOG'} ...
  ,{'VehAccel_X_Sen'             , 'm/s/s'            , 'axVehCOG'} ...
  ,{'VehSpd'                      , 'km/h'             , 'vVehCOG'} ...
  ,{'VehYawRate_Raw'              , 'deg/s'            , 'yawpVeh'} ...
  ,{'LRW'                         , 'deg'              , 'deltaStWhl'} ...
  ,{'LRW_Gesch'                   , 'deg/s'            , 'deltapStWhl'} ...  
  ,{'RDU_FahrerLenkmoment'        , 'Nm'               , 'TStWhlSens'} ...
  ,{'IPAS_Soll_Lenkmoment'        , 'Nm'               , 'TEpsReq'} ...  
  ,{'ExtSteerReq_Dev2Pth_active'  , '-'                , 'SALaLoIqfm_active'} ...
  ,{'ExtSteerReq_Dev2Pth_y'       , 'm'                , 'SALaLoIqfm_dy'} ...
  ,{'ExtSteerReq_Dev2Pth_psi'     , 'rad'              , 'SALaLoIqfm_psi'} ...
  ,{'ExtSteerReq_Dev2Pth_c0'      , '1/m'              , 'SALaLoIqfm_c0'} ...
  ,{'WhlRPM_FL'                   , 'rpm'              , 'omegaWhFl'} ...
  ,{'WhlRPM_FR'                   , 'rpm'              , 'omegaWhFr'} ...
  ,{'WhlRPM_RL'                   , 'rpm'              , 'omegaWhRl'} ...
  ,{'WhlRPM_RR'                   , 'rpm'              , 'omegaWhRr'} ...
  ,{'Steer_WhlAng'                , 'rad'              , 'deltaStWhl'} ...         % Carmaker
  ,{'Car_v'                       , 'm/s'              , 'vVehCOG'} ... 
  ,{'Car_vFL'                     , 'm/s'              , 'vWhFl'} ...   
  ,{'Car_vFR'                     , 'm/s'              , 'vWhFr'} ...   
  ,{'Car_vRL'                     , 'm/s'              , 'vWhRl'} ...   
  ,{'Car_vRR'                     , 'm/s'              , 'vWhRr'} ...   
  ,{'PT_WFL_rotv'                 , 'rad/s'            , 'omegaWhFl'} ...   
  ,{'PT_WFR_rotv'                 , 'rad/s'            , 'omegaWhFr'} ...   
  ,{'PT_WRL_rotv'                 , 'rad/s'            , 'omegaWhRl'} ...   
  ,{'PT_WRR_rotv'                 , 'rad/s'            , 'omegaWhRr'} ...   
  ,{'Car_Yaw'                     , 'rad'              , 'yawVeh'} ... 
  ,{'Car_YawRate'                 , 'rad/s'            , 'yawpVeh'} ... 
  ,{'Car_Gen_ax_1'                , 'm/s/s'            , 'axVehCOG'} ... 
  ,{'Car_Gen_ax_1'                , 'm/s/s'            , 'ayVehCOG'} ...   
  ,{'Car_SideSlipAngle'           , 'rad/s'            , 'betaVehCOG'} ...   
  ,{'Car_FzFL'                    , 'N'                , 'FzWhFl'} ...   
  ,{'Car_FzFR'                    , 'N'                , 'FzWhFr'} ...   
  ,{'Car_FzRL'                    , 'N'                , 'FzWhRl'} ...   
  ,{'Car_FzRR'                    , 'N'                , 'FzWhRr'} ...  
  ,{'RPSensor_RPS0m_x'                  , 'm'           ,'xSpur'} ... 
  ,{'RPSensor_RPS0m_y'                  , 'm'           ,'ySpur'} ... 
  ,{'Car_BdySensor_BSFrontAxle_Pos_0_x' , 'm'           ,'xVehVA'} ... 
  ,{'Car_BdySensor_BSFrontAxle_Pos_0_y' , 'm'           ,'yVehVA'} ... 
  ,{'ACLNX_COG'                         , 'm/s/s'       , 'axVehCOG'} ... 
  ,{'ACLNY_COG'                         , 'm/s/s'       , 'ayVehCOG'} ... 
  ,{'ACLNZ_COG'                         , 'm/s/s'       , 'azVehCOG'} ... 
  ,{'V_VEH_COG'                         , 'km/h'        , 'vVehCOG'} ... 
  ,{'VYAW_VEH'                          , 'deg/s'       , 'yawpVeh'} ... 
  ,{'AVL_STEA_DV'                       , 'deg'         , 'deltaStWhl'} ... 
  ,{'AVL_STEAV_DV'                      , 'deg/s'       , 'deltapStWhl'} ... 
  ,{'AVL_STEA_FTAX_WHL'                 , 'deg'         , 'yawWhFA'} ... 
  ,{'AVL_ANG_ACPD'                      , '%'           , 'aGasPedal'} ... 
  ,{'AVL_ANG_ACPD_VIRT'                 , '%'           , 'aGasPedalVirt'} ... 
  ,{'MILE_VEH'                          , 'm'           , 'sVehCOG'} ... 
  ,{'AVL_STMOM_DV_ACT'                  , 'Nm'          , 'TStWhlSens'} ... 
  ,{'AVL_QUAN_EES_WHL_FLH'              , '-'           , 'pulseWhFl'} ... 
  ,{'AVL_QUAN_EES_WHL_FRH'              , '-'           , 'pulseWhFr'} ... 
  ,{'AVL_QUAN_EES_WHL_RLH'              , '-'           , 'pulseWhRl'} ... 
  ,{'AVL_QUAN_EES_WHL_RRH'              , '-'           , 'pulseWhRr'} ...
  ,{'AVL_RPM_WHL_FLH'                   , 'rad/s'       , 'omegaWhFl'} ... 
  ,{'AVL_RPM_WHL_FRH'                   , 'rad/s'       , 'omegaWhFr'} ... 
  ,{'AVL_RPM_WHL_RLH'                   , 'rad/s'       , 'omegaWhRl'} ... 
  ,{'AVL_RPM_WHL_RRH'                   , 'rad/s'       , 'omegaWhRr'} ... 
  ,{'AVL_RPM_BAX_RED'                   , 'U/min'       , 'omegaWhRA'} ... 
  ,{'MILE_WHL_FLH'                      , 'cm'          , 'sWhFl'} ... 
  ,{'MILE_WHL_FRH'                      , 'cm'          , 'sWhFr'} ... 
  ,{'MILE_WHL_RLH'                      , 'cm'          , 'sWhRl'} ... 
  ,{'MILE_WHL_RRH'                      , 'cm'          , 'sWhRr'} ... 
  ,{'ATTA_ESTI'                         , 'deg'         , 'betaVehCOG'} ... 
  ,{'ATTAV_ESTI'                        , 'deg/s'       , 'betapVehCOG'} ... 
  ,{'TAR_STMOM_DV_ACT'                  , 'Nm'          , 'TEpsReq'} ...
  ,{'AVL_WMOM_PT_SUM'                   , 'Nm'          , 'TDriveAxisAct'} ...
  ,{'AVL_WMOM_PT_SUM_MAX'               , 'Nm'          , 'TDriveAxisMax'} ...
  ,{'AVL_WMOM_PT_SUM_DTORQ_BOT'         , 'Nm'          , 'TDriveAxisMin'} ...
  ,{'Brk_Torque'                        , 'Nm'          , 'TBrakeAxisAct'} ...
  
  
  
  
  };
  % Signalliste mit den neuen Namen
  %{name_new                 , unit_new           , comment_new}
  c_siglist_out = ...
  {{'ayVehCOG'              , 'm/s/s',         'Querbeschleunigung Schwerpunkt Fahrzeug'} ...
  ,{'axVehCOG'              , 'm/s/s',         'Längsbeschleunigung Schwerpunkt Fahrzeug'} ...
  ,{'azVehCOG'              , 'm/s/s',         'Vertikalbeschleunigung Schwerpunkt Fahrzeug'} ...
  ,{'vVehCOG'               , 'm/s',           'Fahrzeuggeschwindigkeit'} ...
  ,{'sVehCOG'               , 'm',             'zurückgelegter Weg'} ...
  ,{'aGasPedal'             , '%',             'Gaspedalstellung'} ...
  ,{'aGasPedalVirt'         , '%',             'virtuelle Gaspedalstellung'} ...
  ,{'vWhFl'                 , 'm/s',           'Geschwindigkeit am Rad in Radebene horizontal vorne links'} ...
  ,{'vWhFr'                 , 'm/s',           'Geschwindigkeit am Rad in Radebene horizontal vorne rechts'} ...
  ,{'vWhRl'                 , 'm/s',           'Geschwindigkeit am Rad in Radebene horizontal hinten links'} ...
  ,{'vWhRr'                 , 'm/s',           'Geschwindigkeit am Rad in Radebene horizontal hinten rechts'} ...
  ,{'omegaWhFl'             , 'rad/s',         'Raddrehgeschwindigkeit in Radebene vorne links'} ...
  ,{'omegaWhFr'             , 'rad/s',         'Raddrehgeschwindigkeit in Radebene vorne rechts'} ...
  ,{'omegaWhRl'             , 'rad/s',         'Raddrehgeschwindigkeit in Radebene hinten links'} ...
  ,{'omegaWhRr'             , 'rad/s',         'Raddrehgeschwindigkeit in Radebene hinten rechts'} ...
  ,{'omegaWhRA'             , 'rad/s',         'Raddrehgeschwindigkeit Hinterachse'} ...
  ,{'pulseWhFl'             , '-',             'Anzahl der gemessenen Raddrehpulse  vorne links'} ...
  ,{'pulseWhFr'             , '-',             'Anzahl der gemessenen Raddrehpulse vorne rechts'} ...
  ,{'pulseWhRl'             , '-',             'Anzahl der gemessenen Raddrehpulse hinten links'} ...
  ,{'pulseWhRr'             , '-',             'Anzahl der gemessenen Raddrehpulse hinten rechts'} ...
  ,{'sWhFl'                 , 'm',             'zurückgelegter Weg Rad vorne links'} ...
  ,{'sWhFr'                 , 'm',             'zurückgelegter Weg Rad vorne rechts'} ...
  ,{'sWhRl'                 , 'm',             'zurückgelegter Weg Rad hinten links'} ...
  ,{'sWhRr'                 , 'm',             'zurückgelegter Weg Rad hinten rechts'} ...
  ,{'betaVehCOG'            , 'rad',           'Schwimmwinkel Schwerpunkt Fahrzeug'} ...
  ,{'betapVehCOG'           , 'rad/s',         'Schwimmwinkelgeschwindigkeit Schwerpunkt Fahrzeug'} ...
  ,{'yawVeh'                , 'rad',           'Gierwinkel Fahrzeug'} ...
  ,{'yawpVeh'               , 'rad/s',         'Gierwinkelgeschwindigkeit Fahrzeug'} ...
  ,{'deltaStWhl'            , 'rad',           'Lenkradwinkel'} ...
  ,{'deltapStWhl'           , 'rad/s',         'Lenkradwinkelgeschw'} ...
  ,{'deltaV'                , 'rad',           'Lenkradwinkel am Rad bezogen auf Vorderachse'} ...
  ,{'deltapV'               , 'rad/s',         'Lenkradwinkelgeschw. am Rad bezogen auf Vorderachse'} ...
  ,{'deltaStWhlReq'         , 'rad',           'Solllenkradwinkel'} ...
  ,{'deltaLReq'             , 'rad',           'Solllenkradwinkel am Rad bezogen auf Vorderachse'} ...
  ,{'TStWhlSens'            , 'Nm',            'sensiertes Handmoment Lenkrad'} ...
  ,{'TEpsReq'               , 'Nm',            'angefordertes EPS-Moment'} ...
  ,{'FzWhFl'                , 'N',             'Radaufstandskraft vorne links'} ...
  ,{'FzWhFr'                , 'N',             'Radaufstandskraft vorne rechts'} ...
  ,{'FzWhRl'                , 'N',             'Radaufstandskraft hinten links'} ...
  ,{'FzWhRr'                , 'N',             'Radaufstandskraft hinten rechts'} ...
  ,{'SALaLoIqfm_active'     , '-',             ''} ...
  ,{'SALaLoIqfm_dy'         , 'm',             ''} ...
  ,{'SALaLoIqfm_psi'        , 'rad',           ''} ...
  ,{'SALaLoIqfm_c0'         , '1/m',           ''} ...
  ,{'xSpur'                 , 'm',             'x-Spur Vorderachse'} ...
  ,{'ySpur'                 , 'm',             'y-Spur Vorderachse'} ...
  ,{'xVehVA'                , 'm',             'x-Fzg Vorderachse Mitte'} ...
  ,{'yVehVA'                , 'm',             'y-Fzg Vorderachse Mitte'} ...
  ,{'TDriveAxisAct'         , 'Nm',            'aktuelles Antriebsmoment bezogen auf die AntriebsAchse'} ...
  ,{'TDriveAxisMax'         , 'Nm',            'maximales Antriebsmoment bezogen auf die AntriebsAchse'} ...
  ,{'TDriveAxisMin'         , 'Nm',            'maximales Schleppmoment (negativ) bezogen auf die AntriebsAchse'} ...
  ,{'TBrakeAxisAct'         , 'Nm',            'aktuelles Bremsmoment (negativ) bezogen auf die Achse gesamt'} ...
  };
end
