function e = cg_read_ecal_channel_CanSurveillancePb(d,channel_name)

  ii = str_find_f(channel_name,'Pb');
  if( ii > 0 )
    name_channel = channel_name(1:max(1,ii-1));
  else
    name_channel = channel_name;
  end
 
  sigliste     = {{'maxDrivingTq.first'    , 1,'Nm'  ,'double'     ,1,''} ...
                 ,{'maxDrivingTq.second'   , 1,'Nm'  ,'double'     ,1,''} ...
                 ,{'BsgBased_VehicleSpeed' , 1,'m/s'  ,'double'     ,1,''} ...
                 ,{'parkingBrReq'      , 1,'-'  ,'int'     ,0,''} ...
                 ,{'reqMotorTq.first'      , 1,'Nm'  ,'double'     ,1,''} ...
                 ,{'reqMotorTq.second'      , 1,'Nm'  ,'double'     ,1,''} ...
                 ,{'brakeTqReq'      , 1,'Nm'  ,'double'     ,1,''} ...  
                 ,{'cal_Torque_demand'      , 1,'Nm'  ,'double'     ,1,''} ... 
                 ,{'VehicleSpeed' , 1,'m/s'  ,'double'     ,1,''} ...
                 ,{'OsOut.OS_OUT_1_REQUESTED_TORQUE',1,'Nm','double',1,''} ...
                 ,{'OsOut.OS_OUT_2_REQUESTED_TORQUE',1,'Nm','double',1,''} ...
                 ,{'OsOut.OS_OUT_1_BrakeTorqueRequest',1,'Nm','double',1,''} ...
                 ,{'OsIn.OS_IN_VehicleSpeed',1,'km/h','double',1,''} ...
                 ,{'OsIn.OS_IN_VehicleSpeedSign',1,'-','int',0,''} ...
                 ,{'OsIn.OS_IN_FourWheelRefSpeed_Cha',1,'km/h','double',1,''} ...
                 ,{'OsIn.OS_IN_VehicleSpeedSign_Cha',1,'-','int',0,''} ...
                 ,{'OsIn.OS_IN_LongAccel',1,'m/s/s','double',1,''} ...
                 ,{'OsIn.OS_IN_PC_CAN_Command_Speed',1,'m/s','double',1,''} ...
                 ,{'OsIn.OS_IN_PC_CAN_Command_Accel',1,'m/s/s','double',1,''} ...
                 ,{'OsIn.OS_IN_Motion_Command_Speed',1,'m/s','double',1,''} ...
                 ,{'OsIn.OS_IN_Motion_Command_Accel',1,'m/s/s','double',1,''} ...
                 ,{'OsIn.OS_IN_DemandedDrivingDirection',1,'-','int',0,''} ...
                 ,{'OsIn.OS_IN_BrakingPressure',1,'bar','double',1,''} ...
                 ,{'OsIn.OS_IN_0_ACTUAL_TORQUE',1,'Nm','double',1,''} ...
                 ,{'OsIn.OS_IN_1_ACTUAL_TORQUE',1,'Nm','double',1,''} ...
                 ,{'OsIn.OS_IN_2_ACTUAL_TORQUE',1,'Nm','double',1,''} ...
                 ,{'OsIn.OS_IN_3_ACTUAL_TORQUE',1,'Nm','double',1,''} ...
                 ,{'OsIn.OS_IN_ParkBrakeBindingStatus',1,'-','int',0,''} ... 
                 ,{'OsIn.OS_IN_0_HW_FAILURE',1,'-','int',0,''} ...                  
                 ,{'OsIn.OS_IN_1_HW_FAILURE',1,'-','int',0,''} ...                  
                 ,{'OsIn.OS_IN_2_HW_FAILURE',1,'-','int',0,''} ...                  
                 ,{'OsIn.OS_IN_3_HW_FAILURE',1,'-','int',0,''} ... 
                 ,{'OsIn.OS_IN_ParkBrakeReqInProgress',1,'-','int',0,''} ...                    
                 ,{'xBoxRaw.speed',1,'m/s','double',1,''} ...
                 ,{'xBoxRaw.accel',1,'m/s/s','double',1,''} ...
                 ,{'xBoxRaw.steerFront',1,'rad','double',1,''} ...
                 ,{'xBoxRaw.steerRear',1,'rad','double',1,''} ...
                 ,{'xBoxRaw.drivingDirection',1,'-','int',0,''} ...
                 ,{'xBoxRaw.deadManDetected',1,'-','int',0,''} ...
                 ,{'OsOut.OS_OUT_1_ParkingBrakeRequest',1,'-','int',0,''} ... 
                 };                 

  e = struct([]);
  
  [e,time] = cg_read_ecal_channel_read_timestamp(e,d,name_channel);
  
%   ndata = length(d.data);
%    
%   timestamp = zeros(ndata,1);
%   for j=1:ndata
%     timestamp(j) = d.data{j}.header.timestamp;
%   end
%   if( isfield(d,'timestamps') )
%     time = double(d.timestamps)*1.0e-6;
%   else
%     time = double(timestamp)*1.0e-6;
%   end
%   
%   e = e_data_add_value(e,[name_channel,'_timestamp'],'us','time stamp',time,timestamp,0);
  
  e = cg_read_ecal_channel_read_signals(e,name_channel,time,d,sigliste);

%   for i=1:length(sigliste)
%     ee = cg_read_ecal_channel_signal(sigliste{i},d.data,time,name_channel);
%     e  = merge_struct_f(e,ee);
%   end
  
% e = e_data_rename_signal(e,[name_channel,'_header_timestamp'],[name_channel,'_timestamp']);
  
end