function eout = cg_read_tacc_channel_RelevantObjectData(e)

  eout = [];
  c_names = fieldnames(e);
  n       = length(c_names);
% Channels zuordnen
signals = {'RelevantObjectData_id' ...
          ,'RelevantObjectData_timestamp_us' ...
          ,'RelevantObjectData_x_m' ...
          ,'RelevantObjectData_y_m' ...
          ,'RelevantObjectData_vx_abs_mps' ...
          ,'RelevantObjectData_vy_abs_mps' ...
          ,'RelevantObjectData_vx_rel_mps' ...
          ,'RelevantObjectData_vy_rel_mps' ...
          ,'RelevantObjectData_recognized_type' ...
          };
usignals = {'-' ...
          ,'us' ...
          ,'m' ...
          ,'m' ...
          ,'m/s' ...
          ,'m/s' ...
          ,'m/s' ...
          ,'m/s' ...
          ,'-' ...
          };
csignals = {'' ...
          ,'' ...
          ,'' ...
          ,'' ...
          ,'' ...
          ,'' ...
          ,'' ...
          ,'' ...
          ,'' ...
          };
lsignals = [0 ...
          ,0 ...
          ,0 ...
          ,0 ...
          ,0 ...
          ,0 ...
          ,0 ...
          ,0 ...
          ,0 ...
          ];
% signals = {'Obj_id' ...
%           ,'isValid' ...
%           ,'Obj_timestamp' ...
%           ,'Obj_x_m' ...
%           ,'Obj_y_m' ...
%           ,'Obj_vx_abs_mps' ...
%           ,'Obj_vy_abs_mps' ...
%           ,'Obj_vx_rel_mps' ...
%           ,'Obj_vy_rel_mps' ...
%           ,'Obj_recognized_type' ...
%           };

  for i=1:n
    
    for j = 1:length(signals)
      
      if( strcmp(c_names{i},signals{j}) )
       [tin,vin] = elim_nicht_monoton(e.(c_names{i}).time,e.(c_names{i}).vec);
       
       eout.(signals{j}).time = double(tin);
       eout.(signals{j}).vec  = double(vin);
       eout.(signals{j}).unit = usignals{j};
       eout.(signals{j}).comment = csignals{j};
       eout.(signals{j}).lin     = lsignals(j);
      end
       
    end
  end
end