function eout = cg_read_tacc_channel_GpsRawData(e)

  eout = [];
  c_names = fieldnames(e);
  n       = length(c_names);
% Channels zuordnen
signals = {'GpsRawData_gpsMsg_course' ...
          ,'GpsRawData_gpsMsg_lat' ...
          ,'GpsRawData_gpsMsg_lon' ...
          ,'GpsRawData_timestamp' ...
          };
usignals = {'deg' ...
          ,'deg' ...
          ,'deg' ...
          ,'us' ...
          };
csignals = {'driving course east is zero' ...
          ,'lateral postion' ...
          ,'longitudinal position' ...
          ,'TimeStamp' ...
          };
lsignals = [1 ...
          ,1 ...
          ,1 ...
          ,1 ...
          ];

  for i=1:n
    
    for j = 1:length(signals)
      
      if( strcmp(c_names{i},signals{j}) )
       [tin,vin] = elim_nicht_monoton(e.(c_names{i}).time,e.(c_names{i}).vec);
       
       eout.(signals{j}).time = tin;
       eout.(signals{j}).vec  = vin;
       eout.(signals{j}).unit = usignals{j};
       eout.(signals{j}).comment = csignals{j};
       eout.(signals{j}).lin     = lsignals(j);
      end
       
    end
  end
end