function [Channels,Headers,nCChanHead] = cg_read_protobuf_names
  CChanHead = {};
  CChanHead = cell_add(CChanHead,{'ESA2VehDsrdTraj','CMsgVehicleDesiredTraj'},1);             % 1
  CChanHead = cell_add(CChanHead,{'LaneRecognition','CMsgLaneRecognition'}    ,1);            % 2
  CChanHead = cell_add(CChanHead,{'VehiclePose','CMsgVehiclePose'}             ,1);           % 3
  CChanHead = cell_add(CChanHead,{'VehicleDynamics','CMsgVehicleDynamics'}    ,1);            % 4
  CChanHead = cell_add(CChanHead,{'RelevantObjectData','CMsgRelevantObjectData'} ,1);         % 5
  CChanHead = cell_add(CChanHead,{'GpsRawData','CGps2NetFrameMsg'}       ,1);                 % 6
  CChanHead = cell_add(CChanHead,{'MFCImage','CMsgCameraImage'}        ,1);                   % 7
  CChanHead = cell_add(CChanHead,{'GenericObjectList','CMsgGenericEnvObjectList'} ,1);        % 8
  CChanHead = cell_add(CChanHead,{'TargetLane','CMsgTargetLane'}         ,1);                 % 9
  CChanHead = cell_add(CChanHead,{'HAPSVehDsrdTraj','CMsgVehicleDesiredTraj'} ,1);            % 10
  CChanHead = cell_add(CChanHead,{'PRORETAVehDsrdTraj','CMsgVehicleDesiredTraj'} ,1);         % 11
  CChanHead = cell_add(CChanHead,{'ArbiCurvRequest','CMsgExtCurvRequest'}     ,1);            % 12
  CChanHead = cell_add(CChanHead,{'ArbiDev2PthRequest','CMsgArbiDev2PthRequest'} ,1);         % 13
  CChanHead = cell_add(CChanHead,{'AD2PCurvRequest','CMsgExtCurvRequest'}     ,1);            % 14
  CChanHead = cell_add(CChanHead,{'AD2PRequest','CMsgExtDev2PthRequest'}  ,1);                % 15
  CChanHead = cell_add(CChanHead,{'CanMsgLatCtrl','CCanMsgLatCtrl'}         ,1);              % 16
  CChanHead = cell_add(CChanHead,{'VehicleDynamicsIn','TVehicleDyn'}            ,1);          % 17
  CChanHead = cell_add(CChanHead,{'PowerTrainIn','TPowerTrain'}            ,1);               % 18
  CChanHead = cell_add(CChanHead,{'LCCVehDsrdTraj','CMsgVehicleDesiredTraj'} ,1);             % 19
  CChanHead = cell_add(CChanHead,{'CarSwitchesIn','TCarSwitches'}          ,1);               % 20
  CChanHead = cell_add(CChanHead,{'Test1VehDsrdTraj','CMsgVehicleDesiredTraj'} ,1);           % 21
  CChanHead = cell_add(CChanHead,{'AD2PDev2PthRequest','CMsgExtDev2PthRequest'}  ,1);         % 22 
  CChanHead = cell_add(CChanHead,{'Vpu4IQF1','CMsgVpu4IQF1'}           ,1);                   % 23
  CChanHead = cell_add(CChanHead,{'GlobalPosVBox','CGlobalPosEstMsg'}       ,1);              % 24
  CChanHead = cell_add(CChanHead,{'PowerTrain','CMsgPowertrain'}         ,1);                 % 25
  CChanHead = cell_add(CChanHead,{'VehicleBehavior','CMsgBehaviorPlanner'}    ,1);            % 26
  CChanHead = cell_add(CChanHead,{'EHorizon','CMsgEHorizon'}           ,1);                   % 27
  CChanHead = cell_add(CChanHead,{'ParkingSpaceDescription','CMsgParkingSpaceDescription'} ,1);    % 28
  CChanHead = cell_add(CChanHead,{'ParkingSpaceDescriptionCorrected','CMsgParkingSpaceDescription'} ,1); % 29
  CChanHead = cell_add(CChanHead,{'VehiclePoseCorrected','CMsgVehiclePose'}  ,1);             % 30
  CChanHead = cell_add(CChanHead,{'VehiclePoseCorrected_replay','CMsgVehiclePose'}  ,1);      % 31
  CChanHead = cell_add(CChanHead,{'PlannerVRequest','CMsgExtVeloRequest'} ,1);                % 32
  CChanHead = cell_add(CChanHead,{'PlannerVehDsrdTraj','CMsgVehicleDesiredTraj' } ,1);        % 33
  CChanHead = cell_add(CChanHead,{'ArbiARequest','CMsgArbiARequest'} ,1);                     % 34
  CChanHead = cell_add(CChanHead,{'ArbiVRequest','CMsgArbiVRequest'} ,1);                     % 35
  CChanHead = cell_add(CChanHead,{'ArbiBrkPressRequest','CMsgArbiBrkPressRequest'} ,1);       % 36
  CChanHead = cell_add(CChanHead,{'GlobalPosRT4000','CGlobalPosEstMsg'} ,1);                  % 37
  CChanHead = cell_add(CChanHead,{'RT4000DataIn','CRT4000DataMsg'} ,1);                       % 38
  CChanHead = cell_add(CChanHead,{'PoseOffsetCorrect','CMsgPoseOffsetCorrect'} ,1);           % 39 
  CChanHead = cell_add(CChanHead,{'V2xFusionCheck_1','CV2xFusionCheckMsg'} ,1);               % 40
  CChanHead = cell_add(CChanHead,{'AD2PVehDsrdTraj','CMsgVehicleDesiredTraj'} ,1);            % 41
  CChanHead = cell_add(CChanHead,{'AD2PDebug','CArbiDev2PthDebugMsg'} ,1);                    % 42
  CChanHead = cell_add(CChanHead,{'TrajectoryRequestFrenet','CMsgVehicleDesiredTraj'} ,1);    % 43
  CChanHead = cell_add(CChanHead,{'PeopleMoverVehDsrdTraj','CMsgVehicleDesiredTraj'} ,1);     % 44
  CChanHead = cell_add(CChanHead,{'PlannerVehDsrdTrajPb','pb.ExtRequests.VehicleDesiredTraj'} ,1); % 45
  CChanHead = cell_add(CChanHead,{'VehicleDynamicsInPb','pb.SensorNearData.VehicleDynamics'} ,1);  % 46
  CChanHead = cell_add(CChanHead,{'PowerTrainInPb','pb.SensorNearData.PowerTrain'} ,1);       % 47
  CChanHead = cell_add(CChanHead,{'VehiclePosePb','pb.VehicleMovement.VehiclePose' } ,1);     % 48
  CChanHead = cell_add(CChanHead,{'CarSwitchesInPb','pb.SensorNearData.CarSwitches'} ,1);      % 49
  CChanHead = cell_add(CChanHead,{'AD2PDev2PthRequestPb','pb.ExtRequests.ExtDev2PthRequest' } ,1);             % 50
  CChanHead = cell_add(CChanHead,{'AD2PVehDsrdTrajPb','pb.ExtRequests.VehicleDesiredTraj'} ,1);                % 51
  CChanHead = cell_add(CChanHead,{'PeopleMoverVehDsrdTrajPb','pb.ExtRequests.VehicleDesiredTraj'} ,1);         % 52
  CChanHead = cell_add(CChanHead,{'GlobalPosRT4000Pb','pb.GlobalPosEst'}  ,1);                % 53
  CChanHead = cell_add(CChanHead,{'ADDrivingStrategyPb','pb.Applications.AD.ADDrivingStrategy'} ,1); % 54
  CChanHead = cell_add(CChanHead,{'ADDSARequestPb','pb.ExtRequests.ExtAccelRequest' } ,1);     % 55
  CChanHead = cell_add(CChanHead,{'ADDSVRequestPb','pb.ExtRequests.ExtVeloRequest'} ,1);      % 56
  CChanHead = cell_add(CChanHead,{'ADModeManager','CMsgADModeManager'} ,1);                   % 57
  CChanHead = cell_add(CChanHead,{'ADModeMangerPb','pb.Applications.AD.ADModeManager'} ,1);                   % 58
  CChanHead = cell_add(CChanHead,{'ArbiARequestPb','pb.Arbitration.ArbiARequest'} ,1);          % 59
  CChanHead = cell_add(CChanHead,{'ArbiDrvCtrlRequest','CMsgArbiDriveCtrlRequest'} ,1);       % 60
  CChanHead = cell_add(CChanHead,{'ArbiDrvCtrlRequestPb','pb.Arbitration.ArbiDriveCtrlRequest'} ,1);           % 61
  CChanHead = cell_add(CChanHead,{'ArbiLngDebugOutputPb','pb.Arbitration.ArbLngDebug'},1);     % 62
  CChanHead = cell_add(CChanHead,{'BrakeInPb','pb.SensorNearData.Brake'} ,1);                 % 63
  CChanHead = cell_add(CChanHead,{'CanMsgLongCtrlPb','pb.Arbitration.CanLongCtrl'} ,1);       % 64
  CChanHead = cell_add(CChanHead,{'DrvCtrlVRequestPb','pb.Arbitration.ArbiVRequest'} ,1);    % 65
  CChanHead = cell_add(CChanHead,{'LatCtrlStatPb','pb.Arbitration.LatCtrlStat' } ,1);         % 66
  CChanHead = cell_add(CChanHead,{'LatCtrlStat','' } ,1);                                     % 67
  CChanHead = cell_add(CChanHead,{'ManeuverList','pb.Applications.AD.ADManeuverListMsg'} ,1); % 68
  CChanHead = cell_add(CChanHead,{'SpeedLimitPb','pb.Embedded.SpeedLimit'} ,1);               % 69
  CChanHead = cell_add(CChanHead,{'CanMsgLatCtrlPb','pb.Arbitration.CanLatCtrl'}         ,1); % 70
  CChanHead = cell_add(CChanHead,{'HapsSafetyPb','pb.Applications.HAPS.HapsSafety'}                          ,1); % 71
  CChanHead = cell_add(CChanHead,{'ParkTrackPlannerRequestPb','pb.Applications.HAPS.ParkTrackPlannerRequest'},1); % 72
  CChanHead = cell_add(CChanHead,{'ParkTrainedResponsePb','pb.Applications.HAPS.ParkScenarioResponseTrained'}        ,1); % 73
  CChanHead = cell_add(CChanHead,{'TPVehDsrdTrajPb','pb.ExtRequests.VehicleDesiredTraj'}              ,1);              % 74
  CChanHead = cell_add(CChanHead,{'TrainParkDebugPb','pb.Applications.HAPS.TrainParkDebug'}                  ,1);       % 75
  CChanHead = cell_add(CChanHead,{'ArbiBrkPressRequestPb','pb.Arbitration.ArbiBrkPressRequest'}                  ,1);   % 76
  CChanHead = cell_add(CChanHead,{'ArbiGasPedalRequestPb','pb.Arbitration.ArbiGasPedalRequest'}                  ,1);   % 77
  CChanHead = cell_add(CChanHead,{'ArbiMaxSetspdRequestPb','pb.Arbitration.ArbiMaxSetspdRequest'}                  ,1); % 78
  CChanHead = cell_add(CChanHead,{'ArbiVRequestPb','pb.Arbitration.ArbiVRequest'}                  ,1);                 % 79
  CChanHead = cell_add(CChanHead,{'ArbLngAFFPRequestPb','pb.ExtRequests.ExtAFFPRequest'}                  ,1);          % 80
  CChanHead = cell_add(CChanHead,{'ArbiDriveCtrlRequestPb','pb.Arbitration.ArbiDriveCtrlRequest'}                  ,1); % 81
  CChanHead = cell_add(CChanHead,{'GPVehDsrdTrajPb','pb.ExtRequests.VehicleDesiredTraj'}              ,1);     % 82
  CChanHead = cell_add(CChanHead,{'RT4000DataInPb','pb.VehicleMovement.RT4000Data'} ,1);                       % 83
  CChanHead = cell_add(CChanHead,{'GlobalPosEst','pb.GlobalPosEst'} ,1);                                       % 84
  CChanHead = cell_add(CChanHead,{'TrainParkDebug','pb.Applications.HAPS.TrainParkDebug'} ,1);                 % 85
  CChanHead = cell_add(CChanHead,{'AD2PDebugPb','pb.Arbitration.ArbiDev2PthDebug'} ,1);                        % 86
  CChanHead = cell_add(CChanHead,{'Vpu4IQF1Pb','pb.ControlVectorActivity.Vpu4IQF1'}           ,1);             % 87
  CChanHead = cell_add(CChanHead,{'ParkingSpaceDescriptionPb','pb.ParkingSpaceDescription.ParkingSpaceDescription'} ,1); % 88
  CChanHead = cell_add(CChanHead,{'ParkingSpaceDescriptionCorrectedPb','pb.ParkingSpaceDescription.ParkingSpaceDescription'} ,1); % 89
  CChanHead = cell_add(CChanHead,{'VehiclePoseCorrectedPb','pb.VehicleMovement.VehiclePose'}  ,1);             % 90
  CChanHead = cell_add(CChanHead,{'PoseOffsetCorrectPb','pb.VehicleMovement.PoseOffsetCorrect'} ,1);           % 91 
  CChanHead = cell_add(CChanHead,{'HAPSVehDsrdTrajPb','pb.ExtRequests.VehicleDesiredTraj'} ,1);                % 92
  CChanHead = cell_add(CChanHead,{'WheelTicksInPb','pb.SensorNearData.WheelTicks'} ,1);                        % 93
  CChanHead = cell_add(CChanHead,{'DrvCtrlStrAngRequestPb','pb.ExtRequests.ExtStrAngRequest'} ,1);             % 94
  CChanHead = cell_add(CChanHead,{'DrvCtrlDebugPb','pb.Arbitration.ArbiDev2PthDebug'} ,1);                     % 95
  CChanHead = cell_add(CChanHead,{'VehicleDynamicsPb','pb.SensorNearData.VehicleDynamics'} ,1);                % 96
  CChanHead = cell_add(CChanHead,{'MFCImageRightPb','pb.SensorNearData.MFC.CameraImage'}        ,1);           % 97
  CChanHead = cell_add(CChanHead,{'DrvCtrlDev2PthRequestPb','pb.ExtRequests.ExtDev2PthRequest'}        ,1);    % 98
  CChanHead = cell_add(CChanHead,{'MotionCntrlPlannerRequestPb','pb.Applications.MotionCntrl.MotionCntrlPlannerRequest'}        ,1);       % 99
  CChanHead = cell_add(CChanHead,{'VisuVehDsrdTrajPb','pb.ExtRequests.VehicleDesiredTraj'}        ,1);       % 100
  CChanHead = cell_add(CChanHead,{'LaneMarkersPb',''}        ,1);                                            % 101
  CChanHead = cell_add(CChanHead,{'RoadModelInterfacePb',''}        ,1);                                     % 102
  CChanHead = cell_add(CChanHead,{'RoadModelInterface_SensorBased',''}        ,1);                           % 103
  CChanHead = cell_add(CChanHead,{'HAPSVRequestPb','pb.ExtRequests.ExtVeloRequest'} ,1);   % 104
  CChanHead = cell_add(CChanHead,{'ParkScenarioResponseTrainedPb','pb.Application.HAPS.ParkScenarioResponseTrained'} ,1);   % 105
  CChanHead = cell_add(CChanHead,{'ParkScenarioRequestPb','pb.Application.HAPS.ParkScenarioRequest'} ,1);   % 106
  CChanHead = cell_add(CChanHead,{'TrainParkManagerRequestPb','pb.Application.HAPS.TrainParkMangerRequest'} ,1);   % 107
  CChanHead = cell_add(CChanHead,{'TrainParkPlannerResponsePb','pb.Application.HAPS.TrainParkPlannerResponse'} ,1);   % 108
  CChanHead = cell_add(CChanHead,{'TrainParkLearnPathPb','pb.Application.HAPS.TrainParkPath'} ,1);   % 109
  CChanHead = cell_add(CChanHead,{'TrainParkLearnDebugPb','pb.Application.HAPS.TrainParkLearnDebug'} ,1);   % 109
  CChanHead = cell_add(CChanHead,{'DrvCtrlDebugPb','pb.ExtRequests.DrvCtrlDebug'} ,1);   % 110
  CChanHead = cell_add(CChanHead,{'RoadModelInterface_MapBased',''}        ,1);                           % 111
  CChanHead = cell_add(CChanHead,{'MapMatchedPos',''}        ,1);                           % 112
  CChanHead = cell_add(CChanHead,{'ValetParkingHandoverZonePb',''}        ,1);                           % 113
  CChanHead = cell_add(CChanHead,{'TrainParkLearnResponsePb',''}        ,1);                           % 114
  CChanHead = cell_add(CChanHead,{'GenericObjectListPb',''}        ,1);                           % 115
  CChanHead = cell_add(CChanHead,{'MapMostProbablePath',''}        ,1);                           % 116
  CChanHead = cell_add(CChanHead,{'ParkTrackPb',''}        ,1);                           % 117
  CChanHead = cell_add(CChanHead,{'ParkScenarioResponseStandardPb',''}        ,1);                           % 118
  CChanHead = cell_add(CChanHead,{'TrainParkPlannerDebugPb',''}        ,1);                           % 119
  CChanHead = cell_add(CChanHead,{'TrainParkManagDebugPb',''}        ,1);                           % 120
  CChanHead = cell_add(CChanHead,{'HapsSafetyPb',''}        ,1);                           % 121
  CChanHead = cell_add(CChanHead,{'EstVehPosePb',''}        ,1);                           % 122
  CChanHead = cell_add(CChanHead,{'TrainParkPathPlannerResponsePb',''}        ,1);                           % 123
  CChanHead = cell_add(CChanHead,{'TrainParkPathPlannerDebugPb',''}        ,1);                           % 124
  CChanHead = cell_add(CChanHead,{'ParkingHandoverZoneTrainedPb',''}        ,1);                           % 125
  CChanHead = cell_add(CChanHead,{'TrajectoryRequestPb',''}        ,1);                           % 126
  CChanHead = cell_add(CChanHead,{'CanCtrlRequestPb',''}        ,1);                           % 127
  CChanHead = cell_add(CChanHead,{'MotionReqDebugPb',''}        ,1);                           % 128
  CChanHead = cell_add(CChanHead,{'VehicleDynamicsInOemSensorsPb',''}        ,1);                           % 129
  CChanHead = cell_add(CChanHead,{'RpEcuADCntrlStatusPb',''}        ,1);                           % 130
  CChanHead = cell_add(CChanHead,{'ElectricGateRequestPb',''}        ,1);                           % 131
  CChanHead = cell_add(CChanHead,{'ValetParkPathPlannerResponsePb',''}        ,1);                    % 132
  CChanHead = cell_add(CChanHead,{'ValetParkPathPlannerDebugPb',''}        ,1);                    % 132
  
  
  nCChanHead = length(CChanHead);
  
  Channels   = {};
  Headers   = {};
  for iii=1:nCChanHead
    try
      Channels = cell_add(Channels,CChanHead{iii}{1});
      Headers  = cell_add(Headers,CChanHead{iii}{2});
    catch
      a = 0;
    end
        
  end
end