function e = cg_read_ecal_channel_VExtCarMakerDMCInterface(d,channel_name)

  ii = str_find_f(channel_name,'Pb');
  if( ii > 0 )
    name_channel = channel_name(1:max(1,ii-1));
  else
    name_channel = channel_name;
  end
 
  sigliste     = {{'carmaker.la_front_activate'                     , 1,'-'     ,'int'     ,0,''} ...
                 ,{'carmaker.front_axle_wheel_angle_request'        , 1,'rad'   ,'double'  ,1,''} ... 
                 ,{'carmaker.la_rear_activate'                      , 1,'-'     ,'int'     ,0,''} ...
                 ,{'carmaker.rear_axle_wheel_angle_request'         , 1,'rad'   ,'double'  ,1,''} ... 
                 ,{'carmaker.lo_activate'                           , 1,'-'     ,'int'     ,0,''} ...
                 ,{'carmaker.accel_req'                             , 1,'m/s/s' ,'double'  ,1,''} ... 
                 ,{'carmaker.gear_lever_req'                        , 1,'-'     ,'int'     ,0,'0:Manual, 1:D, 2:R, 3:N, 4:P '} ...
                 ,{'carmaker.epb_req'                               , 1,'-'     ,'int'     ,0,''} ...
                 ,{'carmaker.maneuver_finished'                     , 1,'-'     ,'int'     ,0,''} ...
                 ,{'ad_motion_control.la_kmc_status'                , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.la_dmc_activate' , 1,'-'      ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.front_axle_wheel_angle_request', 1,'rad'     ,'double'     ,1,''} ...     
                 ,{'ad_motion_control.rear_axle_wheel_angle_request', 1,'rad'     ,'double'     ,1,''} ...     
                 ,{'ad_motion_control.lo_kmc_status'                , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.cruising_lo_dmc_activate'     , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.parking_lo_dmc_activate'      , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.accel_req'                    , 1,'m/s/s' ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.velocity_req'                 , 1,'m/s'     ,'double'     ,1,''} ...     
                 ,{'ad_motion_control.distance_to_stop'             , 1,'m'     ,'double'     ,1,''} ...     
                 ,{'ad_motion_control.epb_req'                      , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.hold_req'                     , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.emergency_hold_req'           , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.gear_lever_req'               , 1,'-'     ,'int'     ,0,'0:Manual, 1:D, 2:R, 3:N, 4:P '} ...     
                 ,{'ad_motion_control.gear_switch_req'              , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.debug_lat_lcc_angle_req'      , 1,'rad'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_lat_lfc_angle_req'      , 1,'rad'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_lat_dyc_p_angle_req'    , 1,'rad'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_lat_dyc_i_angle_req'    , 1,'rad'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_lat_dyc_d_angle_req'    , 1,'rad'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_lat_hdc_angle_req'      , 1,'rad'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_long_dec_p_req'         , 1,'m/s'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_long_dec_i_req'         , 1,'m/s'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_long_dec_d_req'         , 1,'m/s'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_long_vec_p_req'         , 1,'m/s/s'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_long_vec_d_req'         , 1,'m/s/s'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_lat_hdc_beta_des'       , 1,'m/s/s'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.debug_lat_hdc_beta_des'       , 1,'rad'   ,'double'  ,1,''} ...     
                 ,{'ad_motion_control.lat_version'                  , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'ad_motion_control.long_version'                 , 1,'-'     ,'int'     ,0,''} ...     
                 ,{'dist_to_stop_control.delta_s_dist_to_stop'      , 1,'m'     ,'double'     ,1,''} ...     
                 ,{'dist_to_stop_control.vel_req_dist_to_stop'      , 1,'m/s'     ,'double'     ,1,''} ...     
                 ,{'dist_to_stop_control.acc_req_dist_to_stop'      , 1,'m/s/s'     ,'double'     ,1,''} ...     
                 
                 };                 

  e    = struct([]);
  
  [e,time] = cg_read_ecal_channel_read_timestamp(e,d,name_channel);
  
%   ndata = length(d.data);
%    
%   timestamp = zeros(ndata,1);
%   for j=1:ndata
%     timestamp(j) = d.data{j}.header.timestamp;
%   end
%   if( isfield(d,'timestamps') )
%     time = double(d.timestamps)*1.0e-6;
%   else
%     time = double(timestamp)*1.0e-6;
%   end
%   
%   e = e_data_add_value(e,[name_channel,'_timestamp'],'us','time stamp',time,timestamp,0);
  
  e = cg_read_ecal_channel_read_signals(e,name_channel,time,d,sigliste);

%   for i=1:length(sigliste)
%     ee = cg_read_ecal_channel_signal(sigliste{i},d.data,time,name_channel);
%     e  = merge_struct_f(e,ee);
%   end
  
% e = e_data_rename_signal(e,[name_channel,'_header_timestamp'],[name_channel,'_timestamp']);
  
end