function e = modify_convert_ecal_template_e(e)

  
  if(  isfield(e,'VehiclePose_x_m') && isfield(e,'VehiclePose_x_ra_m') ...
    && isfield(e,'VehiclePose_y_m') && isfield(e,'VehiclePose_y_ra_m') ...
    )
    
    vec = sqrt((e.VehiclePose_x_m.vec-e.VehiclePose_x_ra_m.vec).^2 ...
              + (e.VehiclePose_y_m.vec-e.VehiclePose_y_ra_m.vec).^2);
            
    e = e_data_add_signal(e,'VehiclePose_wheelbase_m' ...
                           ,'m' ...
                           ,'' ...
                           ,e.VehiclePose_x_m.time ...
                           ,vec ...
                           ,1);

    
  end
    
    
  
end