function c = BuildPlotFile_template_plot(iplot,ttitle,unit,yminmaxflag,yminmax)

  if( ~exist('unit','var') )
    unit = '';
  end
  if( ~isempty(unit) ) 
    unit = sprintf('[%s]',unit);
  end
% ,'xmin',            0 ...
% ,'xmax',            1 ...
% ,'ymin',            -2 ...
% ,'ymax',            2 ...
% );
% opitional auch:
% ,'title_set',       1 ....
% ,'x_label_set',       1 ....
% ,'y_label_set',       1 ....
% ,'xlim_set',          1 ....
% ,'ylim_set',          1 ....

  if( yminmaxflag )
    t1 = sprintf('    ,''ylim_set'',         %i ...',1);
    t2 = sprintf('    ,''ymin'',             %f ...',yminmax(1));
    t3 = sprintf('    ,''ymax'',             %f ...',yminmax(2));
  else
    t1 = sprintf('    ,''ylim_set'',         %i ...',0);
    t2 = sprintf('    ,''ymin'',             %f ...',0.0);
    t3 = sprintf('    ,''ymax'',             %f ...',0.0);
  end
  c = ...
  {'    % =========================================================================' ...
  ,sprintf('    %% %i. Plot',iplot) ...
  ,'    % =========================================================================' ...
  ,sprintf('    iplot = %i;',iplot) ...
  ,'    s_fig = plot_set_plot_f(s_fig,iplot ...' ...
  ,'    ,''grid_set'',        1 ...' ...
  ,sprintf('    ,''title'',           ''%s'' ...',ttitle) ...
  ,sprintf('    ,''y_label'',         ''%s'' ...',unit) ...
  ,'    ,''legend_set'',      1 ...' ...
  ,t1 ...
  ,t2 ...
  ,t3 ...
  ,'    );' ...
  ,'    iplotdata = 0;' ...
  };
end