function c = BuildPlotFile_template_end(xytype,xunit)


  if( ~isempty(xytype) ) % 'x-y-plot'
    zeile1 = sprintf('    s_fig.s_plot(length(s_fig.s_plot)).x_label     = [''%s''];',xunit);
    zeile2 = '    s_fig.s_plot(length(s_fig.s_plot)).x_label_set = 1;';
  else
    zeile1 = '    s_fig.s_plot(length(s_fig.s_plot)).x_label     = [q.x_sig_name,'' '',q.x_unit_name];';
    zeile2 = '    s_fig.s_plot(length(s_fig.s_plot)).x_label_set = 1;';
  end
  c = ...
  {'' ...
  ,'    % =========================================================================' ...
  ,'    % bot_title' ...
  ,'    for idataset = 1:ndataset' ...
  ,'      idata = dataset(idataset);' ...
  ,'      s_fig.s_plot(length(s_fig.s_plot)).bot_title{idata} = q.file_list{idata};' ...
  ,'      s_fig.s_plot(length(s_fig.s_plot)).bot_title_set    = 1;' ...
  ,'    end' ...
  ,'' ...
  ,'    % x_label' ...
  ,zeile1 ...
  ,zeile2 ...
  ,'' ...
  ,'    % Plotten' ...
  ,'    if( plot_check_if_data_f(s_fig) )' ...
  ,'      [hfig,okay,haxis] = plot_f(s_fig);' ...
  ,'      if( q.plot_move_pos  )' ...
  ,'        q.Pindex = figure_add_axis_val(q.Pindex,hfig,haxis);' ...
  ,'      end' ...
  ,'    end' ...
  ,'  end' ...
  ,'end' ...
  };
