function varname0 = change_varname(varname0)
%
% varname1 = change_varname(varname0)
% Ändert alle nicht erlaubten Zeichen
%

ctext = {'ä','ae' ...
        ;'Ä','Ae' ...
        ;'ü','ue' ...
        ;'Ü','Ue' ... 
        ;'ö','oe' ...
        ;'Ö','Oe' ...
        ;'ß','ss' ...
        ;'-','_' ...
        ;'+','_' ...
        ;'*','_' ...
        ;'#','_' ...
        ;'/','_' ...
        ;'.','_' ...
        ;' ','_' ...
        ;'(','_' ...
        ;')','_' ...
        ;'[','_' ...
        ;']','_' ...
        ;'{','_' ...
        ;'}','_' ...
        };

[n,m] = size(ctext);
for i=1:n
    
    varname0 = str_change_f(varname0,ctext{i,1},ctext{i,2});
end

