function   [c_siglist_in,c_siglist_out] = d_data_change_signal_name_list
  % Signalliste mit den bestehenden Namen
  %{name_in                  , unit_in            , name_new}
  c_siglist_in = ...
  {{'PrivCAN_VehAccel_Y'                  , 'm/s/s'            , 'ayVehCOG'} ...              % VPU-CAN
  ,{'PrivCAN_VehAccel_X_Sen'              , 'm/s/s'            , 'axVehCOG'} ...
  ,{'PrivCAN_VehSpd'                      , 'km/h'             , 'vVehCOG'} ...
  ,{'PrivCAN_VehYawRate_Raw'              , 'deg/s'            , 'yawpVeh'} ...
  ,{'PrivCAN_StW_Angl'                    , 'deg'              , 'deltaStWhl'} ...
  ,{'PrivCAN_StW_AnglSpd'                 , 'deg/s'            , 'deltapStWhl'} ...  
  ,{'PrivCAN_RDU_FahrerLenkmoment'        , 'Nm'               , 'TStWhlSens'} ...
  ,{'PrivCAN_IPAS_Soll_Lenkmoment'        , 'Nm'               , 'TEpsReq'} ...  
  ,{'PrivCAN_ExtSteerReq_Dev2Pth_active'  , '-'                , 'SALaLoIqfm_active'} ...
  ,{'PrivCAN_ExtSteerReq_Dev2Pth_y'       , 'm'                , 'SALaLoIqfm_dy'} ...
  ,{'PrivCAN_ExtSteerReq_Dev2Pth_psi'     , 'rad'              , 'SALaLoIqfm_psi'} ...
  ,{'PrivCAN_ExtSteerReq_Dev2Pth_c0'      , '1/m'              , 'SALaLoIqfm_c0'} ...
  ,{'Steer_WhlAng'                , 'rad'              , 'deltaStWhl'} ...         % Carmaker
  ,{'Car_v'                       , 'm/s'              , 'vVehCOG'} ... 
  ,{'Car_vFL'                     , 'm/s'              , 'vWhFl'} ...   
  ,{'Car_vFR'                     , 'm/s'              , 'vWhFr'} ...   
  ,{'Car_vRL'                     , 'm/s'              , 'vWhRl'} ...   
  ,{'Car_vRR'                     , 'm/s'              , 'vWhRr'} ...   
  ,{'Car_CFL_rz'                  , 'rad'              , 'deltaWhFl'} ...   
  ,{'Car_CFR_rz'                  , 'rad'              , 'deltaWhFr'} ...   
  ,{'Car_CRL_rz'                  , 'rad'              , 'deltaWhRl'} ...   
  ,{'Car_CRR_rz'                  , 'rad'              , 'deltaWhRr'} ...   
  ,{'PT_WFL_rotv'                 , 'rad/s'            , 'omegaWhFl'} ...   
  ,{'PT_WFR_rotv'                 , 'rad/s'            , 'omegaWhFr'} ...   
  ,{'PT_WRL_rotv'                 , 'rad/s'            , 'omegaWhRl'} ...   
  ,{'PT_WRR_rotv'                 , 'rad/s'            , 'omegaWhRr'} ...   
  ,{'Car_Yaw'                     , 'rad'              , 'yawVeh'} ... 
  ,{'Car_YawRate'                 , 'rad/s'            , 'yawpVeh'} ... 
  ,{'Car_Gen_ax_1'                , 'm/s/s'            , 'axVehCOG'} ... 
  ,{'Car_Gen_ay_1'                , 'm/s/s'            , 'ayVehCOG'} ...   
  ,{'Car_SideSlipAngle'           , 'rad/s'            , 'betaVehCOG'} ...   
  ,{'Car_FzFL'                    , 'N'                , 'FzWhFl'} ...   
  ,{'Car_FzFR'                    , 'N'                , 'FzWhFr'} ...   
  ,{'Car_FzRL'                    , 'N'                , 'FzWhRl'} ...   
  ,{'Car_FzRR'                    , 'N'                , 'FzWhRr'} ...  
  ,{'RPSensor_RPS0m_x'                  , 'm'           ,'xSpur'} ... 
  ,{'RPSensor_RPS0m_y'                  , 'm'           ,'ySpur'} ... 
  ,{'BodySensor_BSFrontAxle_Pos_0_x'    , 'm'           ,'xVehVA'} ... 
  ,{'BodySensor_BSFrontAxle_Pos_0_y'    , 'm'           ,'yVehVA'} ... 
  ,{'PT_ACLNX_COG'                         , 'm/s/s'       , 'axVehCOG'} ...     % BMW
  ,{'PT_ACLNY_COG'                         , 'm/s/s'       , 'ayVehCOG'} ... 
  ,{'PT_V_VEH_COG'                         , 'km/h'        , 'vVehCOG'} ... 
  ,{'PT_VYAW_VEH'                          , 'deg/s'       , 'yawpVeh'} ... 
  ,{'PT_AVL_STEA_DV'                       , 'deg'         , 'deltaStWhl'} ... 
  ,{'PT_AVL_STEAV_DV'                      , 'deg/s'       , 'deltapStWhl'} ... 
  ,{'PT_AVL_STEA_FTAX_WHL'                 , 'deg'         , 'yawWhFA'} ... 
  ,{'PT_AVL_ANG_ACPD'                      , '%'           , 'aGasPedal'} ... 
  ,{'PT_AVL_ANG_ACPD_VIRT'                 , '%'           , 'aGasPedalVirt'} ... 
  ,{'PT_MILE_VEH'                          , 'm'           , 'sVehCOG'} ... 
  ,{'PT_AVL_STMOM_DV_ACT'                  , 'Nm'          , 'TStWhlSens'} ... 
  ,{'PT_AVL_QUAN_EES_WHL_FLH'              , '-'           , 'pulseWhFl'} ... 
  ,{'PT_AVL_QUAN_EES_WHL_FRH'              , '-'           , 'pulseWhFr'} ... 
  ,{'PT_AVL_QUAN_EES_WHL_RLH'              , '-'           , 'pulseWhRl'} ... 
  ,{'PT_AVL_QUAN_EES_WHL_RRH'              , '-'           , 'pulseWhRr'} ...
  ,{'PT_AVL_RPM_WHL_FLH'                   , 'rad/s'       , 'omegaWhFl'} ... 
  ,{'PT_AVL_RPM_WHL_FRH'                   , 'rad/s'       , 'omegaWhFr'} ... 
  ,{'PT_AVL_RPM_WHL_RLH'                   , 'rad/s'       , 'omegaWhRl'} ... 
  ,{'PT_AVL_RPM_WHL_RRH'                   , 'rad/s'       , 'omegaWhRr'} ... 
  ,{'PT_AVL_RPM_BAX_RED'                   , 'U/min'       , 'omegaWhRA'} ... 
  ,{'PT_MILE_WHL_FLH'                      , 'cm'          , 'sWhFl'} ... 
  ,{'PT_MILE_WHL_FRH'                      , 'cm'          , 'sWhFr'} ... 
  ,{'PT_MILE_WHL_RLH'                      , 'cm'          , 'sWhRl'} ... 
  ,{'PT_MILE_WHL_RRH'                      , 'cm'          , 'sWhRr'} ... 
  ,{'PT_ATTA_ESTI'                         , 'deg'         , 'betaVehCOG'} ... 
  ,{'PT_ATTAV_ESTI'                        , 'deg/s'       , 'betapVehCOG'} ... 
  ,{'PT_TAR_STMOM_DV_ACT'                  , 'Nm'          , 'TEpsReq'} ... 
  ,{'PrivCAN_RP_Req_Press_FL'              , 'bar'         , 'pBrFlRef'} ...
  ,{'PrivCAN_RP_Req_Press_FR'              , 'bar'         , 'pBrFrRef'} ...
  ,{'PrivCAN_RP_Req_Press_RL'              , 'bar'         , 'pBrRlRef'} ...
  ,{'PrivCAN_RP_Req_Press_RR'              , 'bar'         , 'pBrRrRef'} ...
  ,{'PrivCAN_RP_Mod_Press_FL'              , 'bar'         , 'pBrFlMod'} ...
  ,{'PrivCAN_RP_Mod_Press_FR'              , 'bar'         , 'pBrFrMod'} ...
  ,{'PrivCAN_RP_Mod_Press_RL'              , 'bar'         , 'pBrRlMod'} ...
  ,{'PrivCAN_RP_Mod_Press_RR'              , 'bar'         , 'pBrRrMod'} ...
  };
  % Signalliste mit den neuen Namen
  %{name_new                 , unit_new           , comment_new}
  c_siglist_out = ...
  {{'ayVehCOG'              , 'm/s/s',         'Querbeschleunigung Schwerpunkt Fahrzeug'} ...
  ,{'axVehCOG'              , 'm/s/s',         'Längsbeschleunigung Schwerpunkt Fahrzeug'} ...
  ,{'vVehCOG'               , 'm/s',           'Fahrzeuggeschwindigkeit'} ...
  ,{'sVehCOG'               , 'm',             'zurückgelegter Weg'} ...
  ,{'aGasPedal'             , '%',             'Gaspedalstellung'} ...
  ,{'aGasPedalVirt'         , '%',             'virtuelle Gaspedalstellung'} ...
  ,{'vWhFl'                 , 'm/s',           'Geschwindigkeit am Rad in Radebene horizontal vorne links'} ...
  ,{'vWhFr'                 , 'm/s',           'Geschwindigkeit am Rad in Radebene horizontal vorne rechts'} ...
  ,{'vWhRl'                 , 'm/s',           'Geschwindigkeit am Rad in Radebene horizontal hinten links'} ...
  ,{'vWhRr'                 , 'm/s',           'Geschwindigkeit am Rad in Radebene horizontal hinten rechts'} ...
  ,{'omegaWhFl'             , 'rad/s',         'Raddrehgeschwindigkeit in Radebene vorne links'} ...
  ,{'omegaWhFr'             , 'rad/s',         'Raddrehgeschwindigkeit in Radebene vorne rechts'} ...
  ,{'omegaWhRl'             , 'rad/s',         'Raddrehgeschwindigkeit in Radebene hinten links'} ...
  ,{'omegaWhRr'             , 'rad/s',         'Raddrehgeschwindigkeit in Radebene hinten rechts'} ...
  ,{'omegaWhRA'             , 'rad/s',         'Raddrehgeschwindigkeit Hinterachse'} ...
  ,{'pulseWhFl'             , '-',             'Anzahl der gemessenen Raddrehpulse  vorne links'} ...
  ,{'pulseWhFr'             , '-',             'Anzahl der gemessenen Raddrehpulse vorne rechts'} ...
  ,{'pulseWhRl'             , '-',             'Anzahl der gemessenen Raddrehpulse hinten links'} ...
  ,{'pulseWhRr'             , '-',             'Anzahl der gemessenen Raddrehpulse hinten rechts'} ...
  ,{'sWhFl'                 , 'm',             'zurückgelegter Weg Rad vorne links'} ...
  ,{'sWhFr'                 , 'm',             'zurückgelegter Weg Rad vorne rechts'} ...
  ,{'sWhRl'                 , 'm',             'zurückgelegter Weg Rad hinten links'} ...
  ,{'sWhRr'                 , 'm',             'zurückgelegter Weg Rad hinten rechts'} ...
  ,{'betaVehCOG'            , 'rad',           'Schwimmwinkel Schwerpunkt Fahrzeug'} ...
  ,{'betapVehCOG'           , 'rad/s',         'Schwimmwinkelgeschwindigkeit Schwerpunkt Fahrzeug'} ...
  ,{'yawVeh'                , 'rad',           'Gierwinkel Fahrzeug'} ...
  ,{'yawpVeh'               , 'rad/s',         'Gierwinkelgeschwindigkeit Fahrzeug'} ...
  ,{'deltaStWhl'            , 'rad',           'Lenkradwinkel'} ...
  ,{'deltapStWhl'           , 'rad/s',         'Lenkradwinkelgeschw'} ...
  ,{'deltaL'                , 'rad',           'Lenkradwinkel am Rad bezogen auf Vorderachse'} ...
  ,{'deltapL'               , 'rad/s',         'Lenkradwinkelgeschw. am Rad bezogen auf Vorderachse'} ...
  ,{'deltaStWhlReq'         , 'rad',           'Solllenkradwinkel'} ...
  ,{'deltaLReq'             , 'rad',           'Solllenkradwinkel am Rad bezogen auf Vorderachse'} ...
  ,{'deltaWhFl'             , 'rad',           'Lenkradwinkel am Rad vorne links'} ...
  ,{'deltaWhFr'             , 'rad',           'Lenkradwinkel am Rad vorne rechts'} ...
  ,{'deltaWhRl'             , 'rad',           'Lenkradwinkel am Rad hinten links'} ...
  ,{'deltaWhRr'             , 'rad',           'Lenkradwinkel am Rad hinten rechts'} ...  
  ,{'TStWhlSens'            , 'Nm',            'sensiertes Handmoment Lenkrad'} ...
  ,{'TEpsReq'               , 'Nm',            'angefordertes EPS-Moment'} ...
  ,{'FzWhFl'                , 'N',             'Radaufstandskraft vorne links'} ...
  ,{'FzWhFr'                , 'N',             'Radaufstandskraft vorne rechts'} ...
  ,{'FzWhRl'                , 'N',             'Radaufstandskraft hinten links'} ...
  ,{'FzWhRr'                , 'N',             'Radaufstandskraft hinten rechts'} ...
  ,{'SALaLoIqfm_active'     , '-',             ''} ...
  ,{'SALaLoIqfm_dy'         , 'm',             ''} ...
  ,{'SALaLoIqfm_psi'        , 'rad',           ''} ...
  ,{'SALaLoIqfm_c0'         , '1/m',           ''} ...
  ,{'xSpur'                 , 'm',             'x-Spur Vorderachse'} ...
  ,{'ySpur'                 , 'm',             'y-Spur Vorderachse'} ...
  ,{'xVehVA'                , 'm',             'x-Fzg Vorderachse Mitte'} ...
  ,{'yVehVA'                , 'm',             'y-Fzg Vorderachse Mitte'} ...
  ,{'pBrFlRef'              , 'bar',           'Radreferenzdruck vorne links'} ...
  ,{'pBrFrRef'              , 'bar',           'Radreferenzdruck vorne rechts'} ...
  ,{'pBrRlRef'              , 'bar',           'Radreferenzdruck hinten links'} ...
  ,{'pBrRrRef'              , 'bar',           'Radreferenzdruck hinten rechts'} ...
  ,{'pBrFlMod'              , 'bar',           'Radmodelldruck vorne links'} ...
  ,{'pBrFrMod'              , 'bar',           'Radmodelldruck vorne rechts'} ...
  ,{'pBrRlMod'              , 'bar',           'Radmodelldruck hinten links'} ...
  ,{'pBrRrMod'              , 'bar',           'Radmodelldruck hinten rechts'} ...
  };
end
