function plo = make_plot_traj_seg_plot_figure_sv_seg_egoPosCross(plo,egoPos,Axle,q)

    set_plot_standards
    
    % line
    if( ~isfield(plo,'line') )
      plo.line = struct([]);
    end
    nline = length(plo.line)+1;
    
    index=such_index(egoPos.time,q.t0);
    
    x0 = egoPos.(Axle).sdistvec(index);
    y0 = egoPos.vvec(index);
        
    plo.line(nline).h = ...
      line('Parent'        ,plo.h_axes(1) ...
          ,'XData'         ,x0 ...
          ,'YData'         ,y0 ...
          ,'Color'         ,PlotStandards.Mschwarz ...
          ,'LineWidth'     ,1 ...
          ,'LineStyle'     ,'none' ...
          ,'Marker'        ,'*' ...
          ,'MarkerSize'    ,20 ...
          ,'Visible'       ,'on');
        
     
end
