function  plo = make_plot_traj_seg_plot_figure_xy_seg_waypoint(plo,iseg,waypoint,q)

    set_plot_standards
    
    % line
    if( ~isfield(plo,'line') )
      plo.line = struct([]);
    end
    nline = length(plo.line)+1;
    plo.line(nline).h = ...
      line('Parent'        ,plo.h_axes(1) ...
          ,'XData'         ,waypoint.xPos ...
          ,'YData'         ,waypoint.yPos ...
          ,'Color'         ,PlotStandards.Farbe{nline} ...
          ,'LineStyle'     ,'none' ...
          ,'Marker'        ,waypoint.marker ...
          ,'MarkerSize'    ,15 ...
          ,'Visible'       ,'on');
        
   % legend
   tt = sprintf('%s%i',waypoint.legText,iseg);
   plo.clegText = cell_add(plo.clegText,tt);
  
end
