function  plo = make_plot_traj_seg_plot_figure_xy_seg_traj(plo,iseg,traj,Axle,q)

    set_plot_standards
    
    % line
    if( ~isfield(plo,'line') )
      plo.line = struct([]);
    end
    nline = length(plo.line)+1;
    plo.line(nline).h = ...
      line('Parent'        ,plo.h_axes(1) ...
          ,'XData'         ,traj.(Axle).xvec + traj.(Axle).offsetX ...
          ,'YData'         ,traj.(Axle).yvec + traj.(Axle).offsetY ...
          ,'Color'         ,PlotStandards.Farbe{nline} ...
          ,'LineWidth'     ,traj.(Axle).lineWidth ...
          ,'LineStyle'     ,traj.(Axle).lineStyle ...
          ,'Marker'        ,traj.(Axle).marker ...
          ,'MarkerSize'    ,max(1,traj.(Axle).marker_size + traj.(Axle).marker_size_di * (iseg-1)) ...
          ,'Visible'       ,'on');
        
   % legend
   tt = sprintf('%s%i',traj.(Axle).legText,iseg);
   if( (abs(traj.(Axle).offsetX) > 0.0005) || (abs(traj.(Axle).offsetY) > 0.0005) )
     tt = sprintf('%s(%5.2f,%5.2f)',tt,traj.(Axle).offsetX,traj.(Axle).offsetY);
   end
   plo.clegText = cell_add(plo.clegText,tt);
  
end
