function okay = proof_cformat(str_format)
%
% okay = proof_cformat(str_format)
%
% Prüft auf Standard C-Format
%
  okay = 1;
  tt = str_change_f(str_format,'  ',' ');
  ctt = str_split(tt,' ');
  nctt = length(ctt);
  if( nctt == 1 )        
     if(  ~strcmp(tt,'float') ...
       && ~strcmp(tt,'double') ...
       && ~strcmp(tt,'char') ...
       && ~strcmp(tt,'short') ...
       && ~strcmp(tt,'int') ...
       && ~strcmp(tt,'long') ...
       )
       okay = 0;
     end
  else
     if(  ~strcmp(ctt{1},'signed') ...
       && ~strcmp(ctt{1},'unsigned') ...
       )
       okay = 0;
     elseif(  ~strcmp(ctt{2},'float') ...
           && ~strcmp(ctt{2},'double') ...
           && ~strcmp(ctt{2},'char') ...
           && ~strcmp(ctt{2},'short') ...
           && ~strcmp(ctt{2},'int') ...
           && ~strcmp(ctt{2},'long') ...
           )
         okay = 0;
     end
  end
end