function [okay,errtext,tt] = rtas_build_io_output_single(type,nspace,output,ivar)
  tt = '';
  okay = 1;
  errtext = '';

  switch(type)
    case 'h'   % Header
      for i=1:nspace
        tt = [tt,' '];
      end
      t1 = sprintf('%s %s; /* #RTAS: ''%s.%s'': [o: on, n: %s, u: %s ] */\n' ...
         , output.var(ivar).cformat ...
         , output.var(ivar).cname ...
         , output.cstructname ...
         , output.var(ivar).cname ...
         , output.var(ivar).name ...
         , output.var(ivar).unit ...
         );
        t2 = sprintf('	                                             /* %s       %s */\n' ...
           , output.var(ivar).cunit ...
           , output.var(ivar).comment ...
           );
        tt = [tt,t1,t2];
    case 'u'   % unitconvert
      
      [fac,offset] = get_unit_convert_fac_offset(output.var(ivar).cunit ,output.var(ivar).unit);
      if( (fac ~= 1.0)  || (offset ~= 0.0) )
          
        for i=1:nspace
          tt = [tt,' '];
        end
        t1 = sprintf('%s.%s = %s.%s * %ff + %ff;\n' ...
         , output.cstructname ...
         , output.var(ivar).cname ...
         , output.cstructname ...
         , output.var(ivar).cname ...
         , fac ...
         , offset ...
         );
        tt = [tt,t1];
      end
    case 'mu'   % Matlab unit setzen
      for i=1:nspace
        tt = [tt,' '];
      end
      t1 = sprintf('u.%s = ''%s'';\n' ...
       , output.var(ivar).name ...
       , output.var(ivar).unit ...
       );
      tt = [tt,t1];
      
  end
end    