function [okay,errtext,tt] = rtas_build_io_input_single(type,nspace,input,ivar)
  tt = '';
  okay = 1;
  errtext = '';

  switch(type)
    case 'h'   % Header
      for i=1:nspace
        tt = [tt,' '];
      end
      t1 = sprintf('%s %s; /* #RTAS: ''%s.%s'': [i: on, n: %s ] */\n' ...
         , input.var(ivar).cformat ...
         , input.var(ivar).cname ...
         , input.cstructname ...
         , input.var(ivar).cname ...
         , input.var(ivar).name ...
         );
        t2 = sprintf('	                                             /* %s       %s */\n' ...
           , input.var(ivar).cunit ...
           , input.var(ivar).comment ...
           );
        tt = [tt,t1,t2];
    case 'u'   % unitconvert
      
      [fac,offset] = get_unit_convert_fac_offset(input.var(ivar).unit ,input.var(ivar).cunit);
      if( (fac ~= 1.0)  || (offset ~= 0.0) )
          
        for i=1:nspace
          tt = [tt,' '];
        end
        t1 = sprintf('%s.%s = %s.%s * %ff + %ff;\n' ...
         , input.cstructname ...
         , input.var(ivar).cname ...
         , input.cstructname ...
         , input.var(ivar).cname ...
         , fac ...
         , offset ...
         );
        tt = [tt,t1];
      end
  end
end    