x = rand(5);    % matrix data
inifile('test1.ini','new');
writeKeys = {'measurement','person','name','Primoz Cermelj';...
            'measurement','protocol','id',1;...
            'application','','description.m2','some...';...
            'data','','x',x};
inifile('test1.ini','write',writeKeys,'plain');
        readKeys = {'measurement','person','name','','John Doe';...
                    'measurement','protocol','id','i',0;...
                    'application','','description.m1','','none';...
                    'application','','description.m2','','none';...
                    'data','','x','d',zeros(5)};
        readSett = inifile('test2.ini','read',readKeys);

        readSett
